// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "data.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_splash
void ui_splash_screen_init(void);
void ui_event_splash(lv_event_t * e);
lv_obj_t * ui_splash;


// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
void ui_event_ScreenWeather(lv_event_t * e);
lv_obj_t * ui_ScreenWeather;
lv_obj_t * ui_PanelGaugeGroup1;
void ui_event_ArcGauge1(lv_event_t * e);
lv_obj_t * ui_ArcGauge1;
lv_obj_t * ui_LabelValue1;
lv_obj_t * ui_LabelUnit1;
lv_obj_t * ui_LabelGaugeHeader1;
lv_obj_t * ui_LabelMinValue1;
lv_obj_t * ui_LabelMaxValue1;
lv_obj_t * ui_PanelGaugeGroup2;
void ui_event_ArcGauge2(lv_event_t * e);
lv_obj_t * ui_ArcGauge2;
lv_obj_t * ui_LabelValue2;
lv_obj_t * ui_LabelUnit2;
lv_obj_t * ui_LabelGaugeHeader2;
lv_obj_t * ui_LabelMinValue2;
lv_obj_t * ui_LabelMaxValue2;
lv_obj_t * ui_PanelGaugeGroup3;
void ui_event_ArcGauge3(lv_event_t * e);
lv_obj_t * ui_ArcGauge3;
lv_obj_t * ui_LabelValue3;
lv_obj_t * ui_LabelUnit3;
lv_obj_t * ui_LabelGaugeHeader3;
lv_obj_t * ui_LabelMinValue3;
lv_obj_t * ui_LabelMaxValue3;
lv_obj_t * ui_PanelGaugeGroup4;
void ui_event_ArcGauge4(lv_event_t * e);
lv_obj_t * ui_ArcGauge4;
lv_obj_t * ui_LabelValue4;
lv_obj_t * ui_LabelUnit4;
lv_obj_t * ui_LabelGaugeHeader4;
lv_obj_t * ui_LabelMinValue4;
lv_obj_t * ui_LabelMaxValue4;
lv_obj_t * ui_Label4;

// SCREEN: ui_ScreenSwitch_Node1
void ui_ScreenSwitch_Node1_screen_init(void);
void ui_event_ScreenSwitch(lv_event_t * e);
lv_obj_t * ui_LabelHeader_Node1;
lv_obj_t * ui_ScreenSwitch_Node1;
lv_obj_t * ui_PanelSwitch1_Node1;
lv_obj_t * ui_PanelSwitch2_Node1;
lv_obj_t * ui_PanelSwitch3_Node1;
lv_obj_t * ui_PanelSwitch4_Node1;
lv_obj_t * ui_Switch1_Node1;
lv_obj_t * ui_Switch2_Node1;
lv_obj_t * ui_Switch3_Node1;
lv_obj_t * ui_Switch4_Node1;
lv_obj_t * ui_Spinner1;
// SCREEN: ui_ScreenSwitch_Node2
void ui_ScreenSwitch_Node2_screen_init(void);
void ui_event_ScreenSwitch(lv_event_t * e);
lv_obj_t * ui_LabelHeader_Node2;
lv_obj_t * ui_ScreenSwitch_Node2;
lv_obj_t * ui_PanelSwitch1_Node2;
lv_obj_t * ui_PanelSwitch2_Node2;
lv_obj_t * ui_PanelSwitch3_Node2;
lv_obj_t * ui_PanelSwitch4_Node2;
lv_obj_t * ui_Switch1_Node2;
lv_obj_t * ui_Switch2_Node2;
lv_obj_t * ui_Switch3_Node2;
lv_obj_t * ui_Switch4_Node2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_patternb[1] = {&ui_img_pattern1b1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {        
        if (screenLastOnFocus == 2)
        {
            _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_FADE_ON, 1, 1500, &ui_ScreenWeather_screen_init);
        }
        else if (screenLastOnFocus == 3)
        {
            _ui_screen_change(&ui_ScreenSwitch_Node1, LV_SCR_LOAD_ANIM_FADE_ON, 1, 1500, &ui_ScreenSwitch_Node1_screen_init);
        }
        else if (screenLastOnFocus == 4)
        {
            _ui_screen_change(&ui_ScreenSwitch_Node2, LV_SCR_LOAD_ANIM_FADE_ON, 1, 1500, &ui_ScreenSwitch_Node2_screen_init);
        }        
        
        lockScreenTimer = millis();
    }
    if (event_code == LV_EVENT_ALL)
    {
        lockScreenTimer = millis();
    }    
}
void ui_event_ScreenWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        screenLastOnFocus = 3;
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSwitch_Node1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_ScreenSwitch_Node1_screen_init);
        lockScreenTimer = millis();
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        screenLastOnFocus = 4;
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSwitch_Node2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_ScreenSwitch_Node2_screen_init);
        lockScreenTimer = millis();
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        _ui_screen_change(&ui_splash, LV_SCR_LOAD_ANIM_FADE_ON, 0, 1500, &ui_splash_screen_init);
        lockScreenTimer = millis();
    }
    if (event_code == LV_EVENT_ALL)
    {
        lockScreenTimer = millis();
    } 
    
}
void ui_event_ScreenSwitch_Node1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        screenLastOnFocus = 2;
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_ScreenWeather_screen_init);
        lockScreenTimer = millis();
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        screenLastOnFocus = 4;
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSwitch_Node2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_ScreenSwitch_Node2_screen_init);
        lockScreenTimer = millis();
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        //screenOnFocus = 1;
        _ui_screen_change(&ui_splash, LV_SCR_LOAD_ANIM_FADE_ON, 0, 1500, &ui_splash_screen_init);
        lockScreenTimer = millis();
    }
    if (event_code == LV_EVENT_ALL)
    {
        lockScreenTimer = millis();
    }    
}
void ui_event_Switch1_Node1(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        //LV_LOG_USER("State: %s\n", lv_obj_has_state(obj, LV_STATE_CHECKED) ? "On" : "Off");
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 11 : 10;
    }
}
void ui_event_Switch2_Node1(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 22 : 20;
    }
}
void ui_event_Switch3_Node1(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 33 : 30;
    }
}
void ui_event_Switch4_Node1(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 44 : 40;
    }
}

void ui_event_ScreenSwitch_Node2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        //screenOnFocus = 2;
        screenLastOnFocus = 3;
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenSwitch_Node1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_ScreenSwitch_Node1_screen_init);
        lockScreenTimer = millis();
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        //screenOnFocus = 2;
        screenLastOnFocus = 2;
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 400, &ui_ScreenWeather_screen_init);
        lockScreenTimer = millis();
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        //screenOnFocus = 1;
        _ui_screen_change(&ui_splash, LV_SCR_LOAD_ANIM_FADE_ON, 0, 1500, &ui_splash_screen_init);
        lockScreenTimer = millis();
    }
    if (event_code == LV_EVENT_ALL)
    {
        lockScreenTimer = millis();
    }    
}
void ui_event_Switch1_Node2(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        //LV_LOG_USER("State: %s\n", lv_obj_has_state(obj, LV_STATE_CHECKED) ? "On" : "Off");
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 11 : 10;
    }
}
void ui_event_Switch2_Node2(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 22 : 20;
    }
}
void ui_event_Switch3_Node2(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 33 : 30;
    }
}
void ui_event_Switch4_Node2(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        _SWITCHSTATUS = lv_obj_has_state(obj, LV_STATE_CHECKED) ? 44 : 40;
    }
}

void ui_event_ArcGauge1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue1, target, "", "");
    }
}
void ui_event_ArcGauge2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue2, target, "", "");
    }
}
void ui_event_ArcGauge3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue3, target, "", "");
    }
}
void ui_event_ArcGauge4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue4, target, "", "");
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_splash_screen_init();
    ui_ScreenWeather_screen_init();
    ui_ScreenSwitch_Node1_screen_init();
    ui_ScreenSwitch_Node2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_splash);
}
