// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_splash
void ui_splash_screen_init(void);
void ui_event_splash(lv_event_t * e);
extern lv_obj_t * ui_splash;
// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
void ui_event_ScreenWeather(lv_event_t * e);
extern lv_obj_t * ui_ScreenWeather;
extern lv_obj_t * ui_PanelGaugeGroup1;
void ui_event_ArcGauge1(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge1;
extern lv_obj_t * ui_LabelValue1;
extern lv_obj_t * ui_LabelUnit1;
extern lv_obj_t * ui_LabelGaugeHeader1;
extern lv_obj_t * ui_LabelMinValue1;
extern lv_obj_t * ui_LabelMaxValue1;
extern lv_obj_t * ui_PanelGaugeGroup2;
void ui_event_ArcGauge2(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge2;
extern lv_obj_t * ui_LabelValue2;
extern lv_obj_t * ui_LabelUnit2;
extern lv_obj_t * ui_LabelGaugeHeader2;
extern lv_obj_t * ui_LabelMinValue2;
extern lv_obj_t * ui_LabelMaxValue2;
extern lv_obj_t * ui_PanelGaugeGroup3;
void ui_event_ArcGauge3(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge3;
extern lv_obj_t * ui_LabelValue3;
extern lv_obj_t * ui_LabelUnit3;
extern lv_obj_t * ui_LabelGaugeHeader3;
extern lv_obj_t * ui_LabelMinValue3;
extern lv_obj_t * ui_LabelMaxValue3;
extern lv_obj_t * ui_PanelGaugeGroup4;
void ui_event_ArcGauge4(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge4;
extern lv_obj_t * ui_LabelValue4;
extern lv_obj_t * ui_LabelUnit4;
extern lv_obj_t * ui_LabelGaugeHeader4;
extern lv_obj_t * ui_LabelMinValue4;
extern lv_obj_t * ui_LabelMaxValue4;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_ScreenSwitch_Node1
void ui_ScreenSwitch_Node1_screen_init(void);
void ui_event_ScreenSwitch_Node1(lv_event_t * e);
void ui_event_Switch1_Node1(lv_event_t * e);
void ui_event_Switch2_Node1(lv_event_t * e);
void ui_event_Switch3_Node1(lv_event_t * e);
void ui_event_Switch4_Node1(lv_event_t * e);
extern lv_obj_t * ui_LabelHeader_Node1;
extern lv_obj_t * ui_ScreenSwitch_Node1;
extern lv_obj_t * ui_PanelSwitch1_Node1;
extern lv_obj_t * ui_PanelSwitch2_Node1;
extern lv_obj_t * ui_PanelSwitch3_Node1;
extern lv_obj_t * ui_PanelSwitch4_Node1;
extern lv_obj_t * ui_Switch1_Node1;
extern lv_obj_t * ui_Switch2_Node1;
extern lv_obj_t * ui_Switch3_Node1;
extern lv_obj_t * ui_Switch4_Node1;
// extern lv_obj_t * ui_Spinner1;
// SCREEN: ui_ScreenSwitch_Node2
void ui_ScreenSwitch_Node2_screen_init(void);
void ui_event_ScreenSwitch_Node2(lv_event_t * e);
void ui_event_Switch1_Node2(lv_event_t * e);
void ui_event_Switch2_Node2(lv_event_t * e);
void ui_event_Switch3_Node2(lv_event_t * e);
void ui_event_Switch4_Node2(lv_event_t * e);
extern lv_obj_t * ui_LabelHeader_Node2;
extern lv_obj_t * ui_ScreenSwitch_Node2;
extern lv_obj_t * ui_PanelSwitch1_Node2;
extern lv_obj_t * ui_PanelSwitch2_Node2;
extern lv_obj_t * ui_PanelSwitch3_Node2;
extern lv_obj_t * ui_PanelSwitch4_Node2;
extern lv_obj_t * ui_Switch1_Node2;
extern lv_obj_t * ui_Switch2_Node2;
extern lv_obj_t * ui_Switch3_Node2;
extern lv_obj_t * ui_Switch4_Node2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo4b_png);    // assets/logo4b.png
LV_IMG_DECLARE(ui_img_pattern1b1_png);    // assets/pattern1b1.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
