// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "data.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_PanelNodeSelect;
lv_obj_t * ui_SliderWifiNode;
lv_obj_t * ui_LabelHeader;
lv_obj_t * ui_LabelNode1;
lv_obj_t * ui_LabelNode2;
lv_obj_t * ui_LabelNode3;
lv_obj_t * ui_ButtonRelay1;
lv_obj_t * ui_ButtonRelay2;
lv_obj_t * ui_ButtonRelay3;
lv_obj_t * ui_ButtonRelay4;
lv_obj_t * ui_LabelMainHeader;
lv_obj_t * ui_LabelBtnRelay1;
lv_obj_t * ui_LabelBtnRelay2;
lv_obj_t * ui_LabelBtnRelay3;
lv_obj_t * ui_LabelBtnRelay4;
lv_obj_t * ui_LabelStatus;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_fire[1] = {&ui_img_fire3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 32
//     #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP !=0
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonRelay1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnRelay1Toggle =!BtnRelay1Toggle;

        _SWITCHSTATUS = BtnRelay1Toggle == true ? 11 : 10;
        const char * relayStatus = BtnRelay1Toggle == true ? "ON" : "OFF";
        uint32_t relayLbtColor = BtnRelay1Toggle == true ? (int)230403 : (int)12845827;
        
        _ui_label_set_property(ui_LabelBtnRelay1, _UI_LABEL_PROPERTY_TEXT, relayStatus);
        lv_obj_set_style_text_color(ui_LabelBtnRelay1, lv_color_hex(relayLbtColor), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
void ui_event_ButtonRelay2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnRelay2Toggle =!BtnRelay2Toggle;

        _SWITCHSTATUS = BtnRelay2Toggle == true ? 22 : 20;
        const char * relayStatus = BtnRelay2Toggle == true ? "ON" : "OFF";
        uint32_t relayLbtColor = BtnRelay2Toggle == true ? (int)230403 : (int)12845827;
        
        _ui_label_set_property(ui_LabelBtnRelay2, _UI_LABEL_PROPERTY_TEXT, relayStatus);
        lv_obj_set_style_text_color(ui_LabelBtnRelay2, lv_color_hex(relayLbtColor), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
void ui_event_ButtonRelay3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnRelay3Toggle =!BtnRelay3Toggle;

        _SWITCHSTATUS = BtnRelay3Toggle == true ? 33 : 30;
        const char * relayStatus = BtnRelay3Toggle == true ? "ON" : "OFF";
        uint32_t relayLbtColor = BtnRelay3Toggle == true ? (int)230403 : (int)12845827;
        
        _ui_label_set_property(ui_LabelBtnRelay3, _UI_LABEL_PROPERTY_TEXT, relayStatus);
        lv_obj_set_style_text_color(ui_LabelBtnRelay3, lv_color_hex(relayLbtColor), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
void ui_event_ButtonRelay4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        BtnRelay4Toggle =!BtnRelay4Toggle;

        _SWITCHSTATUS = BtnRelay4Toggle == true ? 44 : 40;
        const char * relayStatus = BtnRelay4Toggle == true ? "ON" : "OFF";
        uint32_t relayLbtColor = BtnRelay4Toggle == true ? (int)230403 : (int)12845827;
        
        _ui_label_set_property(ui_LabelBtnRelay4, _UI_LABEL_PROPERTY_TEXT, relayStatus);
        lv_obj_set_style_text_color(ui_LabelBtnRelay4, lv_color_hex(relayLbtColor), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
void ui_event_SliderWifiNode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        int32_t SliderWifiNode1Level = lv_slider_get_value(ui_SliderWifiNode);
        if (SliderWifiNode1Level > 69 && SliderWifiNode1Level <= 100)
        {
            lv_slider_set_value(ui_SliderWifiNode, 95, LV_ANIM_OFF);
            selectWifiNode = '1';
        }
        else if (SliderWifiNode1Level > 30 && SliderWifiNode1Level <= 69)
        {
            lv_slider_set_value(ui_SliderWifiNode, 50, LV_ANIM_OFF);
            selectWifiNode = '2';
        }
        else if (SliderWifiNode1Level >= 0 && SliderWifiNode1Level <= 30)
        {
            lv_slider_set_value(ui_SliderWifiNode, 0, LV_ANIM_OFF);
            selectWifiNode = '3';
        }
        else 
        {
            lv_slider_set_value(ui_SliderWifiNode, 95, LV_ANIM_OFF);
            selectWifiNode = '1';
        }
        
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
