// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenSwitchNode1_screen_init(void)
{
    ui_ScreenSwitchNode1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitchNode1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSwitchNode1, lv_color_hex(0x58B6F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitchNode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenSwitchNode1, lv_color_hex(0x58F7D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenSwitchNode1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1Node1 = lv_switch_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_Switch1Node1, 135);
    lv_obj_set_height(ui_Switch1Node1, 130);
    lv_obj_set_x(ui_Switch1Node1, -200);
    lv_obj_set_y(ui_Switch1Node1, -50);
    lv_obj_set_align(ui_Switch1Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_main_stop(ui_Switch1Node1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch1Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch1Node1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1Node1, lv_color_hex(0xFE0505), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch1Node1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch1Node1, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch1Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch1Node1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1Node1, lv_color_hex(0xF1EDED), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1Node1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch1Node1, lv_color_hex(0x3E403E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch1Node1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch2Node1 = lv_switch_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_Switch2Node1, 135);
    lv_obj_set_height(ui_Switch2Node1, 130);
    lv_obj_set_x(ui_Switch2Node1, 200);
    lv_obj_set_y(ui_Switch2Node1, -50);
    lv_obj_set_align(ui_Switch2Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_main_stop(ui_Switch2Node1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch2Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch2Node1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch2Node1, lv_color_hex(0xFE0505), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch2Node1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch2Node1, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch2Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch2Node1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch2Node1, lv_color_hex(0xF1EDED), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2Node1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch2Node1, lv_color_hex(0x3E403E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch2Node1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch3Node1 = lv_switch_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_Switch3Node1, 135);
    lv_obj_set_height(ui_Switch3Node1, 130);
    lv_obj_set_x(ui_Switch3Node1, -200);
    lv_obj_set_y(ui_Switch3Node1, 120);
    lv_obj_set_align(ui_Switch3Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_main_stop(ui_Switch3Node1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch3Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch3Node1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch3Node1, lv_color_hex(0xFE0505), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch3Node1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch3Node1, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch3Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch3Node1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch3Node1, lv_color_hex(0xF1EDED), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3Node1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch3Node1, lv_color_hex(0x3E403E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch3Node1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Switch4Node1 = lv_switch_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_Switch4Node1, 135);
    lv_obj_set_height(ui_Switch4Node1, 130);
    lv_obj_set_x(ui_Switch4Node1, 200);
    lv_obj_set_y(ui_Switch4Node1, 120);
    lv_obj_set_align(ui_Switch4Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_main_stop(ui_Switch4Node1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch4Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch4Node1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch4Node1, lv_color_hex(0xFE0505), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch4Node1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Switch4Node1, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Switch4Node1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch4Node1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch4Node1, lv_color_hex(0xF1EDED), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4Node1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switch4Node1, lv_color_hex(0x3E403E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switch4Node1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_ScreenSwitchNode1);
    lv_bar_set_value(ui_Bar2, 255, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 500);
    lv_obj_set_height(ui_Bar2, 10);
    lv_obj_set_x(ui_Bar2, 0);
    lv_obj_set_y(ui_Bar2, -150);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xF4EEEE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Bar2, lv_color_hex(0x48B0A1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Bar2, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Bar2, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelHeaderNode1 = lv_label_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_LabelHeaderNode1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelHeaderNode1, LV_SIZE_CONTENT); 
    lv_obj_set_x(ui_LabelHeaderNode1, 0);
    lv_obj_set_y(ui_LabelHeaderNode1, -190);
    lv_obj_set_align(ui_LabelHeaderNode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeaderNode1, "CONTROL PANEL 1");
    lv_obj_set_style_text_color(ui_LabelHeaderNode1, lv_color_hex(0x17552E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeaderNode1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LabelHeaderNode1, lv_color_hex(0x49DC7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LabelHeaderNode1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSc2Left = lv_btn_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_BtnSc2Left, 40);
    lv_obj_set_height(ui_BtnSc2Left, 29);
    lv_obj_set_x(ui_BtnSc2Left, -377);
    lv_obj_set_y(ui_BtnSc2Left, 222);
    lv_obj_set_align(ui_BtnSc2Left, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BtnSc2Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSc2Left, lv_color_hex(0x58F7D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSc2Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnSc2Left, &ui_img_arrow3_l_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnSc2Left, 155, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSc2Right = lv_btn_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_BtnSc2Right, 40);
    lv_obj_set_height(ui_BtnSc2Right, 29);
    lv_obj_set_x(ui_BtnSc2Right, 377);
    lv_obj_set_y(ui_BtnSc2Right, 222);
    lv_obj_set_align(ui_BtnSc2Right, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BtnSc2Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSc2Right, lv_color_hex(0x58F7D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSc2Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnSc2Right, &ui_img_arrow3_r_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnSc2Right, 155, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSc2LoadStatus = lv_label_create(ui_ScreenSwitchNode1);
    lv_obj_set_width(ui_lbSc2LoadStatus, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lbSc2LoadStatus, LV_SIZE_CONTENT); 
    lv_obj_set_x(ui_lbSc2LoadStatus, 0);
    lv_obj_set_y(ui_lbSc2LoadStatus, 225);
    lv_obj_set_align(ui_lbSc2LoadStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSc2LoadStatus, "Loading new screen. Please, wait ...");
    lv_obj_add_flag(ui_lbSc2LoadStatus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_lbSc2LoadStatus,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lbSc2LoadStatus, lv_color_hex(0x034905), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSc2LoadStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwitch1Node1 = lv_label_create(ui_Switch1Node1);
    lv_obj_set_width(ui_LbSwitch1Node1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LbSwitch1Node1, LV_SIZE_CONTENT); 
    lv_obj_set_align(ui_LbSwitch1Node1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwitch1Node1, "Switch 1");
	
    ui_LbSwitch2Node1 = lv_label_create(ui_Switch2Node1);
    lv_obj_set_width(ui_LbSwitch2Node1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LbSwitch2Node1, LV_SIZE_CONTENT); 
    lv_obj_set_align(ui_LbSwitch2Node1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwitch2Node1, "Switch 2");
	
	ui_LbSwitch3Node1 = lv_label_create(ui_Switch3Node1);
    lv_obj_set_width(ui_LbSwitch3Node1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LbSwitch3Node1, LV_SIZE_CONTENT); 
    lv_obj_set_align(ui_LbSwitch3Node1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwitch3Node1, "Switch 3");
	
	ui_LbSwitch4Node1 = lv_label_create(ui_Switch4Node1);
    lv_obj_set_width(ui_LbSwitch4Node1, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LbSwitch4Node1, LV_SIZE_CONTENT); 
    lv_obj_set_align(ui_LbSwitch4Node1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwitch4Node1, "Switch 4");

    lv_obj_add_event_cb( ui_Switch1Node1,	ui_event_Switch1Node1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_Switch2Node1, 	ui_event_Switch2Node1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_Switch3Node1, 	ui_event_Switch3Node1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_Switch4Node1, 	ui_event_Switch4Node1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSc2Left, ui_event_BtnSc2Left, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSc2Right, ui_event_BtnSc2Right, LV_EVENT_ALL, NULL);
}
