// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenSwitch_Node1_screen_init(void)
{
    ui_ScreenSwitch_Node1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitch_Node1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenSwitch_Node1, &ui_img_pattern1b1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_ScreenSwitch_Node1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeader_Node1 = lv_label_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_LabelHeader_Node1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeader_Node1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeader_Node1, 0);
    lv_obj_set_y(ui_LabelHeader_Node1, -180);
    lv_obj_set_align(ui_LabelHeader_Node1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeader_Node1, "CONTROL PANEL 1");
    lv_obj_set_style_text_color(ui_LabelHeader_Node1, lv_color_hex(0x050AA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeader_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHeader_Node1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHeader_Node1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHeader_Node1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeader_Node1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelHeader_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHeader_Node1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelHeader_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHeader_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHeader_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelHeader_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelHeader_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelHeader_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelHeader_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelHeader_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);    

    ui_PanelSwitch1_Node1 = lv_obj_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_PanelSwitch1_Node1, 320);
    lv_obj_set_height(ui_PanelSwitch1_Node1, 150);
    lv_obj_set_x(ui_PanelSwitch1_Node1, -190);
    lv_obj_set_y(ui_PanelSwitch1_Node1, -50);
    lv_obj_set_align(ui_PanelSwitch1_Node1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSwitch1_Node1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSwitch1_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSwitch1_Node1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSwitch1_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSwitch1_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSwitch1_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSwitch1_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelSwitch1_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelSwitch1_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSwitch1_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSwitch1_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSwitch2_Node1 = lv_obj_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_PanelSwitch2_Node1, 320);
    lv_obj_set_height(ui_PanelSwitch2_Node1, 150);
    lv_obj_set_x(ui_PanelSwitch2_Node1, 190);
    lv_obj_set_y(ui_PanelSwitch2_Node1, -50);
    lv_obj_set_align(ui_PanelSwitch2_Node1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSwitch2_Node1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSwitch2_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSwitch2_Node1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSwitch2_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSwitch2_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSwitch2_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSwitch2_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelSwitch2_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelSwitch2_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSwitch2_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSwitch2_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSwitch3_Node1 = lv_obj_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_PanelSwitch3_Node1, 320);
    lv_obj_set_height(ui_PanelSwitch3_Node1, 150);
    lv_obj_set_x(ui_PanelSwitch3_Node1, -190);
    lv_obj_set_y(ui_PanelSwitch3_Node1, 120);
    lv_obj_set_align(ui_PanelSwitch3_Node1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSwitch3_Node1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSwitch3_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSwitch3_Node1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSwitch3_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSwitch3_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSwitch3_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSwitch3_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelSwitch3_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelSwitch3_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSwitch3_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSwitch3_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSwitch4_Node1 = lv_obj_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_PanelSwitch4_Node1, 320);
    lv_obj_set_height(ui_PanelSwitch4_Node1, 150);
    lv_obj_set_x(ui_PanelSwitch4_Node1, 190);
    lv_obj_set_y(ui_PanelSwitch4_Node1, 120);
    lv_obj_set_align(ui_PanelSwitch4_Node1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSwitch4_Node1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSwitch4_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSwitch4_Node1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSwitch4_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSwitch4_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSwitch4_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSwitch4_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelSwitch4_Node1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelSwitch4_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelSwitch4_Node1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelSwitch4_Node1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1_Node1 = lv_switch_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_Switch1_Node1, 200);
    lv_obj_set_height(ui_Switch1_Node1, 100);
    lv_obj_set_x(ui_Switch1_Node1, -190);
    lv_obj_set_y(ui_Switch1_Node1, -50);
    lv_obj_set_align(ui_Switch1_Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1_Node1, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch2_Node1 = lv_switch_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_Switch2_Node1, 200);
    lv_obj_set_height(ui_Switch2_Node1, 100);
    lv_obj_set_x(ui_Switch2_Node1, 190);
    lv_obj_set_y(ui_Switch2_Node1, -50);
    lv_obj_set_align(ui_Switch2_Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2_Node1, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch3_Node1 = lv_switch_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_Switch3_Node1, 200);
    lv_obj_set_height(ui_Switch3_Node1, 100);
    lv_obj_set_x(ui_Switch3_Node1, -190);
    lv_obj_set_y(ui_Switch3_Node1, 120);
    lv_obj_set_align(ui_Switch3_Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch3_Node1, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch4_Node1 = lv_switch_create(ui_ScreenSwitch_Node1);
    lv_obj_set_width(ui_Switch4_Node1, 200);
    lv_obj_set_height(ui_Switch4_Node1, 100);
    lv_obj_set_x(ui_Switch4_Node1, 190);
    lv_obj_set_y(ui_Switch4_Node1, 120);
    lv_obj_set_align(ui_Switch4_Node1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch4_Node1, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4_Node1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Spinner1 = lv_spinner_create(ui_ScreenSwitch_Node1, 1000, 90);
    // lv_obj_set_width(ui_Spinner1, 200);
    // lv_obj_set_height(ui_Spinner1, 200);
    // lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_ScreenSwitch_Node1, ui_event_ScreenSwitch_Node1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_Switch1_Node1,	ui_event_Switch1_Node1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_Switch2_Node1, 	ui_event_Switch2_Node1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_Switch3_Node1, 	ui_event_Switch3_Node1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_Switch4_Node1, 	ui_event_Switch4_Node1, 	LV_EVENT_ALL, NULL);

}
