// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScreenSwitchBoard
void ui_ScreenSwitchBoard_screen_init(void);
void ui_event_ScreenSwitchBoard(lv_event_t * e);
extern lv_obj_t * ui_ScreenSwitchBoard;
void ui_event_Switch1(lv_event_t * e);
void ui_event_Switch2(lv_event_t * e);
void ui_event_Switch3(lv_event_t * e);
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
// SCREEN: ui_ScreenChart
void ui_ScreenChart_screen_init(void);
void ui_event_ScreenChart(lv_event_t * e);
extern lv_obj_t * ui_ScreenChart;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
