// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenSwitch_screen_init(void)
{
    ui_ScreenSwitch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenSwitch, &ui_img_pattern1b1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_ScreenSwitch, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTempereture1 = lv_obj_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_PanelTempereture1, 320);
    lv_obj_set_height(ui_PanelTempereture1, 150);
    lv_obj_set_x(ui_PanelTempereture1, -190);
    lv_obj_set_y(ui_PanelTempereture1, -50);
    lv_obj_set_align(ui_PanelTempereture1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTempereture1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTempereture1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTempereture1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTempereture1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTempereture1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTempereture1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTempereture1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelTempereture1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelTempereture1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelTempereture1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelTempereture1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHumidity1 = lv_obj_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_PanelHumidity1, 320);
    lv_obj_set_height(ui_PanelHumidity1, 150);
    lv_obj_set_x(ui_PanelHumidity1, 190);
    lv_obj_set_y(ui_PanelHumidity1, -50);
    lv_obj_set_align(ui_PanelHumidity1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHumidity1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHumidity1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHumidity1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHumidity1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHumidity1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHumidity1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHumidity1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelHumidity1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelHumidity1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelHumidity1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelHumidity1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMaxMinTemp1 = lv_obj_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_PanelMaxMinTemp1, 320);
    lv_obj_set_height(ui_PanelMaxMinTemp1, 150);
    lv_obj_set_x(ui_PanelMaxMinTemp1, -190);
    lv_obj_set_y(ui_PanelMaxMinTemp1, 120);
    lv_obj_set_align(ui_PanelMaxMinTemp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMaxMinTemp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelMaxMinTemp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelMaxMinTemp1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMaxMinTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelMaxMinTemp1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMaxMinTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMaxMinTemp1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelMaxMinTemp1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelMaxMinTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelMaxMinTemp1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelMaxMinTemp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPressure1 = lv_obj_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_PanelPressure1, 320);
    lv_obj_set_height(ui_PanelPressure1, 150);
    lv_obj_set_x(ui_PanelPressure1, 190);
    lv_obj_set_y(ui_PanelPressure1, 120);
    lv_obj_set_align(ui_PanelPressure1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPressure1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPressure1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPressure1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPressure1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPressure1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPressure1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPressure1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelPressure1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelPressure1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelPressure1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelPressure1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeader1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelHeader1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeader1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeader1, 0);
    lv_obj_set_y(ui_LabelHeader1, -180);
    lv_obj_set_align(ui_LabelHeader1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeader1, " CONTROL PANEL ");
    lv_obj_set_style_text_color(ui_LabelHeader1, lv_color_hex(0x050AA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHeader1, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHeader1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHeader1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeader1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelHeader1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHeader1, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHeader1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelHeader1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelHeader1, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelHeader1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelHeader1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidity1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelHumidity1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidity1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidity1, 190);
    lv_obj_set_y(ui_LabelHumidity1, -50);
    lv_obj_set_align(ui_LabelHumidity1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidity1, "00.00");
    lv_obj_set_style_text_color(ui_LabelHumidity1, lv_color_hex(0x550909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidity1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHumidity1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHumidity1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHumidity1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumidity1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMaxMinTemp1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelMaxMinTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaxMinTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaxMinTemp1, -190);
    lv_obj_set_y(ui_LabelMaxMinTemp1, 120);
    lv_obj_set_align(ui_LabelMaxMinTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaxMinTemp1, "00.00");
    lv_obj_set_style_text_color(ui_LabelMaxMinTemp1, lv_color_hex(0x550909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMaxMinTemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMaxMinTemp1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMaxMinTemp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMaxMinTemp1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaxMinTemp1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPressure1 = lv_label_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_LabelPressure1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPressure1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPressure1, 190);
    lv_obj_set_y(ui_LabelPressure1, 120);
    lv_obj_set_align(ui_LabelPressure1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPressure1, "00.00");
    lv_obj_set_style_text_color(ui_LabelPressure1, lv_color_hex(0x550909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPressure1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelPressure1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelPressure1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPressure1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPressure1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_Switch1, 200);
    lv_obj_set_height(ui_Switch1, 100);
    lv_obj_set_x(ui_Switch1, -190);
    lv_obj_set_y(ui_Switch1, -50);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch2 = lv_switch_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_Switch2, 200);
    lv_obj_set_height(ui_Switch2, 100);
    lv_obj_set_x(ui_Switch2, 190);
    lv_obj_set_y(ui_Switch2, -50);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch3 = lv_switch_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_Switch3, 200);
    lv_obj_set_height(ui_Switch3, 100);
    lv_obj_set_x(ui_Switch3, -190);
    lv_obj_set_y(ui_Switch3, 120);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch4 = lv_switch_create(ui_ScreenSwitch);
    lv_obj_set_width(ui_Switch4, 200);
    lv_obj_set_height(ui_Switch4, 100);
    lv_obj_set_x(ui_Switch4, 190);
    lv_obj_set_y(ui_Switch4, 120);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0xC40505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenSwitch, ui_event_ScreenSwitch, LV_EVENT_ALL, NULL);

}
