// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenWeather_screen_init(void)
{
    ui_ScreenWeather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenWeather, &ui_img_pattern1b1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_ScreenWeather, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTempereture = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelTempereture, 320);
    lv_obj_set_height(ui_PanelTempereture, 150);
    lv_obj_set_x(ui_PanelTempereture, -190);
    lv_obj_set_y(ui_PanelTempereture, -50);
    lv_obj_set_align(ui_PanelTempereture, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTempereture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTempereture, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTempereture, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTempereture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTempereture, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTempereture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTempereture, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelTempereture, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelTempereture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelTempereture, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelTempereture, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHumidity = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelHumidity, 320);
    lv_obj_set_height(ui_PanelHumidity, 150);
    lv_obj_set_x(ui_PanelHumidity, 190);
    lv_obj_set_y(ui_PanelHumidity, -50);
    lv_obj_set_align(ui_PanelHumidity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHumidity, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHumidity, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHumidity, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHumidity, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelHumidity, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelHumidity, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelHumidity, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMaxMinTemp = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelMaxMinTemp, 320);
    lv_obj_set_height(ui_PanelMaxMinTemp, 150);
    lv_obj_set_x(ui_PanelMaxMinTemp, -190);
    lv_obj_set_y(ui_PanelMaxMinTemp, 120);
    lv_obj_set_align(ui_PanelMaxMinTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMaxMinTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelMaxMinTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelMaxMinTemp, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMaxMinTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelMaxMinTemp, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMaxMinTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMaxMinTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelMaxMinTemp, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelMaxMinTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelMaxMinTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelMaxMinTemp, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPressure = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelPressure, 320);
    lv_obj_set_height(ui_PanelPressure, 150);
    lv_obj_set_x(ui_PanelPressure, 190);
    lv_obj_set_y(ui_PanelPressure, 120);
    lv_obj_set_align(ui_PanelPressure, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPressure, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPressure, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPressure, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPressure, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelPressure, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelPressure, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelPressure, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeader = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeader, -1);
    lv_obj_set_y(ui_LabelHeader, -180);
    lv_obj_set_align(ui_LabelHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeader, " CONTROL PANEL ");
    lv_obj_set_style_text_color(ui_LabelHeader, lv_color_hex(0x050AA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHeader, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHeader, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeader, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelHeader, lv_color_hex(0xC9E1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHeader, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelHeader, lv_color_hex(0x0B03A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempereture = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelTempereture, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempereture, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempereture, -190);
    lv_obj_set_y(ui_LabelTempereture, -50);
    lv_obj_set_align(ui_LabelTempereture, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempereture, "00.00");
    lv_obj_set_style_text_color(ui_LabelTempereture, lv_color_hex(0x550909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempereture, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTempereture, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTempereture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTempereture, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempereture, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidity = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidity, 190);
    lv_obj_set_y(ui_LabelHumidity, -50);
    lv_obj_set_align(ui_LabelHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidity, "00.00");
    lv_obj_set_style_text_color(ui_LabelHumidity, lv_color_hex(0x550909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHumidity, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHumidity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHumidity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumidity, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMaxMinTemp = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelMaxMinTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaxMinTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaxMinTemp, -190);
    lv_obj_set_y(ui_LabelMaxMinTemp, 120);
    lv_obj_set_align(ui_LabelMaxMinTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaxMinTemp, "00.00");
    lv_obj_set_style_text_color(ui_LabelMaxMinTemp, lv_color_hex(0x550909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMaxMinTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMaxMinTemp, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMaxMinTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMaxMinTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaxMinTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPressure = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelPressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPressure, 190);
    lv_obj_set_y(ui_LabelPressure, 120);
    lv_obj_set_align(ui_LabelPressure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPressure, "00.00");
    lv_obj_set_style_text_color(ui_LabelPressure, lv_color_hex(0x550909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelPressure, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelPressure, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPressure, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPressure, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -190);
    lv_obj_set_y(ui_Label4, 0);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "°C");

    ui_Label1 = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 190);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "%");

    ui_Label2 = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -190);
    lv_obj_set_y(ui_Label2, 170);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "°C");

    ui_Label3 = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 190);
    lv_obj_set_y(ui_Label3, 170);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "hPa");
    
    lv_obj_add_event_cb(ui_ScreenWeather, ui_event_ScreenWeather, LV_EVENT_ALL, NULL);

}
