// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
lv_obj_t * ui_ScreenWeather;
lv_obj_t * ui_PanelGaugeGroup1;
void ui_event_ArcGauge1(lv_event_t * e);
lv_obj_t * ui_ArcGauge1;
lv_obj_t * ui_LabelValue1;
lv_obj_t * ui_LabelUnit1;
lv_obj_t * ui_LabelGaugeHeader1;
lv_obj_t * ui_LabelMinValue1;
lv_obj_t * ui_LabelMaxValue1;
lv_obj_t * ui_PanelGaugeGroup2;
void ui_event_ArcGauge2(lv_event_t * e);
lv_obj_t * ui_ArcGauge2;
lv_obj_t * ui_LabelValue2;
lv_obj_t * ui_LabelUnit2;
lv_obj_t * ui_LabelGaugeHeader2;
lv_obj_t * ui_LabelMinValue2;
lv_obj_t * ui_LabelMaxValue2;
lv_obj_t * ui_PanelGaugeGroup3;
void ui_event_ArcGauge3(lv_event_t * e);
lv_obj_t * ui_ArcGauge3;
lv_obj_t * ui_LabelValue3;
lv_obj_t * ui_LabelUnit3;
lv_obj_t * ui_LabelGaugeHeader3;
lv_obj_t * ui_LabelMinValue3;
lv_obj_t * ui_LabelMaxValue3;
lv_obj_t * ui_PanelGaugeGroup4;
void ui_event_ArcGauge4(lv_event_t * e);
lv_obj_t * ui_ArcGauge4;
lv_obj_t * ui_LabelValue4;
lv_obj_t * ui_LabelUnit4;
lv_obj_t * ui_LabelGaugeHeader4;
lv_obj_t * ui_LabelMinValue4;
lv_obj_t * ui_LabelMaxValue4;
lv_obj_t * ui_lbHeaderWeather;
lv_obj_t * ui_lbConnectionWeather;


// SCREEN: ui_ScreenSwitch1
void ui_ScreenSwitch1_screen_init(void);
lv_obj_t * ui_ScreenSwitch1;
lv_obj_t * ui_lbHeaderSwitch1;
lv_obj_t * ui_Switch1a;
lv_obj_t * ui_Switch1b;
lv_obj_t * ui_Switch1c;
lv_obj_t * ui_Switch1d;
lv_obj_t * ui_Switch1e;
lv_obj_t * ui_Switch1f;
lv_obj_t * ui_lbConnectionSwitch1;


// SCREEN: ui_ScreenSwitch2
void ui_ScreenSwitch2_screen_init(void);
lv_obj_t * ui_ScreenSwitch2;
lv_obj_t * ui_lbHeaderSwitch2;
lv_obj_t * ui_Switch2a;
lv_obj_t * ui_Switch2b;
lv_obj_t * ui_Switch2c;
lv_obj_t * ui_Switch2d;
lv_obj_t * ui_Switch2e;
lv_obj_t * ui_Switch2f;
lv_obj_t * ui_lbConnectionSwitch2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_patternb[1] = {&ui_img_pattern1b1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 32
//     #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP !=0
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ArcGauge1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue1, target, "", "");
    }
}
void ui_event_ArcGauge2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue2, target, "", "");
    }
}
void ui_event_ArcGauge3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue3, target, "", "");
    }
}
void ui_event_ArcGauge4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelValue4, target, "", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenWeather_screen_init();
    ui_ScreenSwitch1_screen_init();
    ui_ScreenSwitch2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenSwitch1);
}
