// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_splash
void ui_splash_screen_init(void);
void ui_event_splash(lv_event_t * e);
extern lv_obj_t * ui_splash;
// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
// void ui_event_ScreenWeather(lv_event_t * e);
void ui_event_BtnSc1Left(lv_event_t * e);
void ui_event_BtnSc1Right(lv_event_t * e);
extern lv_obj_t * ui_ScreenWeather;

extern lv_obj_t * ui_BarTemp;
extern lv_obj_t * ui_lbTempMain;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_LbPressure;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_LbAltitude;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_LbHumidity;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_LbTemp;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_BtnSc1Left;
extern lv_obj_t * ui_BtnSc1Right;
extern lv_obj_t * ui_lbSc1LoadStatus;

void ui_ScreenSwitchNode1_screen_init(void);
// void ui_event_ScreenSwitchNode1(lv_event_t * e);
void ui_event_Switch1Node1(lv_event_t * e);
void ui_event_Switch2Node1(lv_event_t * e);
void ui_event_Switch3Node1(lv_event_t * e);
void ui_event_Switch4Node1(lv_event_t * e);
void ui_event_BtnSc2Left(lv_event_t * e);
void ui_event_BtnSc2Right(lv_event_t * e);
extern lv_obj_t * ui_LabelHeaderNode1;
extern lv_obj_t * ui_ScreenSwitchNode1;
extern lv_obj_t * ui_PanelSwitch1Node1;
extern lv_obj_t * ui_PanelSwitch2Node1;
extern lv_obj_t * ui_PanelSwitch3Node1;
extern lv_obj_t * ui_PanelSwitch4Node1;
extern lv_obj_t * ui_Switch1Node1;
extern lv_obj_t * ui_Switch2Node1;
extern lv_obj_t * ui_Switch3Node1;
extern lv_obj_t * ui_Switch4Node1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_BtnSc2Left;
extern lv_obj_t * ui_BtnSc2Right;
extern lv_obj_t * ui_lbSc2LoadStatus;

void ui_ScreenSwitchNode2_screen_init(void);
// void ui_event_ScreenSwitchNode2(lv_event_t * e);
void ui_event_Switch1Node2(lv_event_t * e);
void ui_event_Switch2Node2(lv_event_t * e);
void ui_event_Switch3Node2(lv_event_t * e);
void ui_event_Switch4Node2(lv_event_t * e);
void ui_event_BtnSc3Left(lv_event_t * e);
void ui_event_BtnSc3Right(lv_event_t * e);
extern lv_obj_t * ui_LabelHeaderNode2;
extern lv_obj_t * ui_ScreenSwitchNode2;
extern lv_obj_t * ui_PanelSwitch1Node2;
extern lv_obj_t * ui_PanelSwitch2Node2;
extern lv_obj_t * ui_PanelSwitch3Node2;
extern lv_obj_t * ui_PanelSwitch4Node2;
extern lv_obj_t * ui_Switch1Node2;
extern lv_obj_t * ui_Switch2Node2;
extern lv_obj_t * ui_Switch3Node2;
extern lv_obj_t * ui_Switch4Node2;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_BtnSc3Left;
extern lv_obj_t * ui_BtnSc3Right;
extern lv_obj_t * ui_lbSc3LoadStatus;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_logo4b_png);    // assets/logo4b.png
LV_IMG_DECLARE(ui_img_pattern1b1_png);    // assets/pattern1b1.png
LV_IMG_DECLARE(ui_img_arrow3_r_png);    // assets/pattern1b1.png
LV_IMG_DECLARE(ui_img_arrow3_l_png);    // assets/pattern1b1.png







void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
