// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
extern lv_obj_t * ui_ScreenWeather;
extern lv_obj_t * ui_PanelGaugeGroup1;
void ui_event_ArcGauge1(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge1;
extern lv_obj_t * ui_LabelValue1;
extern lv_obj_t * ui_LabelUnit1;
extern lv_obj_t * ui_LabelGaugeHeader1;
extern lv_obj_t * ui_LabelMinValue1;
extern lv_obj_t * ui_LabelMaxValue1;
extern lv_obj_t * ui_PanelGaugeGroup2;
void ui_event_ArcGauge2(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge2;
extern lv_obj_t * ui_LabelValue2;
extern lv_obj_t * ui_LabelUnit2;
extern lv_obj_t * ui_LabelGaugeHeader2;
extern lv_obj_t * ui_LabelMinValue2;
extern lv_obj_t * ui_LabelMaxValue2;
extern lv_obj_t * ui_PanelGaugeGroup3;
void ui_event_ArcGauge3(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge3;
extern lv_obj_t * ui_LabelValue3;
extern lv_obj_t * ui_LabelUnit3;
extern lv_obj_t * ui_LabelGaugeHeader3;
extern lv_obj_t * ui_LabelMinValue3;
extern lv_obj_t * ui_LabelMaxValue3;
extern lv_obj_t * ui_PanelGaugeGroup4;
void ui_event_ArcGauge4(lv_event_t * e);
extern lv_obj_t * ui_ArcGauge4;
extern lv_obj_t * ui_LabelValue4;
extern lv_obj_t * ui_LabelUnit4;
extern lv_obj_t * ui_LabelGaugeHeader4;
extern lv_obj_t * ui_LabelMinValue4;
extern lv_obj_t * ui_LabelMaxValue4;
extern lv_obj_t * ui_lbHeaderWeather;
extern lv_obj_t * ui_lbConnectionWeather;
// SCREEN: ui_ScreenSwitch1
void ui_ScreenSwitch1_screen_init(void);
extern lv_obj_t * ui_ScreenSwitch1;
extern lv_obj_t * ui_lbHeaderSwitch1;
extern lv_obj_t * ui_Switch1a;
extern lv_obj_t * ui_Switch1b;
extern lv_obj_t * ui_Switch1c;
extern lv_obj_t * ui_Switch1d;
extern lv_obj_t * ui_Switch1e;
extern lv_obj_t * ui_Switch1f;
extern lv_obj_t * ui_lbConnectionSwitch1;
// SCREEN: ui_ScreenSwitch2
void ui_ScreenSwitch2_screen_init(void);
extern lv_obj_t * ui_ScreenSwitch2;
extern lv_obj_t * ui_lbHeaderSwitch2;
extern lv_obj_t * ui_Switch2a;
extern lv_obj_t * ui_Switch2b;
extern lv_obj_t * ui_Switch2c;
extern lv_obj_t * ui_Switch2d;
extern lv_obj_t * ui_Switch2e;
extern lv_obj_t * ui_Switch2f;
extern lv_obj_t * ui_lbConnectionSwitch2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_pattern1b1_png);    // assets/pattern1b1.png



LV_FONT_DECLARE(ui_font_NumberDotsFont);
LV_FONT_DECLARE(ui_font_NumberDotsFont30);
LV_FONT_DECLARE(ui_font_NumbersDigital);
LV_FONT_DECLARE(ui_font_NumbersDigital60);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
