// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "data.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_splash
void ui_splash_screen_init(void);
//void ui_event_splash(lv_event_t * e);
lv_obj_t * ui_splash;

// SCREEN: ui_ScreenWeatherscreen
void ui_ScreenWeather_screen_init(void);
void ui_event_ScreenWeather_previous(lv_event_t * e);
void ui_event_ScreenWeather_next(lv_event_t * e);
lv_obj_t * ui_ScreenWeather;
lv_obj_t * ui_WeatherHeader;
lv_obj_t * ui_WeatherHeader1;
lv_obj_t * ui_iconWeather;
lv_obj_t * ui_iconTemp;
lv_obj_t * ui_iconAirPressure;
lv_obj_t * ui_iconAirHumidity;
lv_obj_t * ui_iconWindSpeed;
lv_obj_t * ui_ContainerWeatherForcast;
lv_obj_t * ui_LbTempText1;
lv_obj_t * ui_LbPressureText1;
lv_obj_t * ui_LbHumidityText1;
lv_obj_t * ui_LbWindspeedText1;
lv_obj_t * ui_LbTempValue1;
lv_obj_t * ui_LbPressureValue1;
lv_obj_t * ui_LbHumidityValue1;
lv_obj_t * ui_LbWindspeedValue1;
lv_obj_t * ui_LbTempUnit1;
lv_obj_t * ui_LbPressureUnit1;
lv_obj_t * ui_LbHumidityUnit1;
lv_obj_t * ui_LbWindspeedUnit1;
lv_obj_t * ui_ContainerIndoorTemp;
lv_obj_t * ui_LbTempText2;
lv_obj_t * ui_LbPressureText2;
lv_obj_t * ui_LbHumidityText2;
lv_obj_t * ui_LbWindspeedText2;
lv_obj_t * ui_LbTempValue2;
lv_obj_t * ui_LbPressureValue2;
lv_obj_t * ui_LbHumidityValue2;
lv_obj_t * ui_LbWindspeedValue2;
lv_obj_t * ui_LbTempUnit2;
lv_obj_t * ui_LbPressureUnit2;
lv_obj_t * ui_LbHumidityUnit2;
lv_obj_t * ui_LbWindspeedUnit2;
lv_obj_t * ui_lbSc1LoadStatus;
lv_obj_t * ui_ScreenWeather_previous;
lv_obj_t * ui_ScreenWeather_next; 
lv_obj_t * ui_LbTimeAndDate;

// SCREEN: ui_ScreenLightControl
void ui_ScreenLightControl_screen_init(void);
lv_obj_t * ui_ScreenLightControl;
lv_obj_t * ui_PanelLightControl;
lv_obj_t * ui_ContainerLightStrip;
lv_obj_t * ui_SwitchLightStripOnOff;
lv_obj_t * ui_LbSwLightStripStatusText;
void ui_event_SwLightStripBrightness(lv_event_t * e);
lv_obj_t * ui_LbSwLightStripBrightness;
lv_obj_t * ui_LbSwBriDesc;
lv_obj_t * ui_ContainerRGBLamp1;
void ui_event_SwitchRGBLamp1OnOff(lv_event_t * e);
lv_obj_t * ui_SwitchRGBLamp1OnOff;
lv_obj_t * ui_LbSwRGBLamp1StatusText;
void ui_event_SwRGBLamp1ColorAndBrightness(lv_event_t * e);
lv_obj_t * ui_LbSwRGBLamp1ColorAndBrightness;
lv_obj_t * ui_LbSwRGBLamp1ColAndBriDesc;
lv_obj_t * ui_ContainerRGBLamp2;
void ui_event_SwitchRGBLamp2OnOff(lv_event_t * e);
lv_obj_t * ui_SwitchRGBLamp2OnOff;
lv_obj_t * ui_LbSwRGBLamp2StatusText;
void ui_event_SwRGBLamp2ColorAndBrightness(lv_event_t * e);
lv_obj_t * ui_LbSwRGBLamp2ColorAndBrightness;
lv_obj_t * ui_LbSwRGBLamp2ColAndBriDesc;
lv_obj_t * ui_ContainerRGBLamp3;
void ui_event_SwitchRGBLamp3OnOff(lv_event_t * e);
lv_obj_t * ui_SwitchRGBLamp3OnOff;
lv_obj_t * ui_LbSwRGBLamp3StatusText;
void ui_event_SwRGBLamp3ColorAndBrightness(lv_event_t * e);
lv_obj_t * ui_SwRGBLamp3ColorAndBrightness;
lv_obj_t * ui_LbSwRGBLamp3ColAndBriDesc;
lv_obj_t * ui_LbSwLightStripDesc;
lv_obj_t * ui_LbSwRGBLamp1Desc;
lv_obj_t * ui_LbSwRGBLamp2Desc;
lv_obj_t * ui_LbSwRGBLamp3Desc;
lv_obj_t * ui_LbLightControlHeader;
void ui_event_ScreenLightControl_previous(lv_event_t * e);
void ui_event_ScreenLightControl_next(lv_event_t * e);
lv_obj_t * ui_ScreenLightControl_previous;
lv_obj_t * ui_ScreenLightControl_next;

// SCREEN: ui_ScreenColorPicker
void ui_ScreenColorPicker_screen_init(void);
lv_obj_t * ui_ScreenColorPicker;
void ui_event_BtnColorPickerDone(lv_event_t * e);
void ui_event_BtnSc3Left(lv_event_t * e);
void ui_event_BtnSc3Right(lv_event_t * e);
void ui_event_ArcColorPicker(lv_event_t * e);
lv_obj_t * ui_BtnColorPickerDone;
lv_obj_t * ui_LbColorPickerBtnText;
lv_obj_t * ui_PanelColorPicker;
lv_obj_t * ui_ArcColorPicker;
lv_obj_t * ui_LbColorPicker;
lv_obj_t * ui_BtnSc3Left;
lv_obj_t * ui_BtnSc3Right; 
lv_obj_t * ui_LbArcColorPickerText;
void ui_event_ArcBrightness(lv_event_t * e);
lv_obj_t * ui_ArcBrightness;
lv_obj_t * ui_LbArcBrightnessText;

// SCREEN: ui_ScreenColorTemp
void ui_ScreenColorTemp_screen_init(void);
lv_obj_t * ui_ScreenColorTemp;
void ui_event_BtnColorTempDone(lv_event_t * e);
lv_obj_t * ui_BtnColorTempDone;
lv_obj_t * ui_LbColorTempBtnText;
lv_obj_t * ui_PanelColorTemp;
lv_obj_t * ui_LbColorTemp;
lv_obj_t * ui_ArcColorTempsLightStrip;
lv_obj_t * ui_LbArcLightStripColorTempText;
void ui_event_ArcBrightnessLightStrip(lv_event_t * e);
void ui_event_ArcColorTempsLightStrip(lv_event_t * e);
lv_obj_t * ui_ArcBrightnessLightStrip;
lv_obj_t * ui_LbArcLightStripBriText;
void ui_event_BtnSc5Left(lv_event_t * e);
void ui_event_BtnSc5Right(lv_event_t * e);
lv_obj_t * ui_BtnSc5Left;
lv_obj_t * ui_BtnSc5Right;


// EVENTS
lv_obj_t * ui____initial_actions0;
// const lv_img_dsc_t * ui_imgset_patternb[1] = {&ui_img_pattern1b1_png};

// CUSTOM VARIABLES
lv_obj_t * uic_Image1;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_blue_background_[1] = {&ui_img_blue_background_5_png};
const lv_img_dsc_t * ui_imgset_patternb[1] = {&ui_img_pattern1b1_png};
const lv_img_dsc_t * ui_imgset_961763586[1] = {&ui_img_999054828};
const lv_img_dsc_t * ui_imgset_443222008[1] = {&ui_img_233333594};
const lv_img_dsc_t * ui_imgset_1604130866[1] = {&ui_img_947629812};
const lv_img_dsc_t * ui_imgset_1779969499[1] = {&ui_img_1668089981};
const lv_img_dsc_t * ui_imgset_789732520[1] = {&ui_img_1578496546};
///////////////////// TEST LVGL SETTINGS ////////////////////

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenWeather_previous(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLightControl, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenLightControl_screen_init);
        _ui_flag_modify(ui_lbSc1LoadStatus, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        screenLastOnFocus = SCREENLIGHTCONTROL;
    }
}
void ui_event_ScreenWeather_next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLightControl, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenLightControl_screen_init);
        _ui_flag_modify(ui_lbSc1LoadStatus, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        screenLastOnFocus = SCREENLIGHTCONTROL;
    }
}
void ui_event_ScreenLightControl_previous(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenWeather_screen_init);
        _ui_flag_modify(ui_lbSc1LoadStatus, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        screenLastOnFocus = WEATHER;
    }
}
void ui_event_ScreenLightControl_next(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {        
        _ui_screen_change(&ui_ScreenWeather, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenWeather_screen_init);
        _ui_flag_modify(ui_lbSc1LoadStatus, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        screenLastOnFocus = WEATHER;
    }
}

void ui_event_ArcColorPicker(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lv_color32_t c32;
        lv_color_t col = lv_colorwheel_get_rgb(ui_ArcColorPicker);
        c32.full = lv_color_to32(col);
        cPickerRGBValue.ch.red = c32.ch.red;
        cPickerRGBValue.ch.green = c32.ch.green;
        cPickerRGBValue.ch.blue = c32.ch.blue;
        cPickRBGColorChanged = true;
    }
}
void ui_event_ArcBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbLampBrightness = lv_arc_get_value(ui_ArcBrightness);
        cPickRBGBrightnessChanged = true;
    }
}
void ui_event_ArcColorTempsLightStrip(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lightstripColorTemp = lv_arc_get_value(ui_ArcColorTempsLightStrip);      
        lightstripColorTempChanged = true;
    }
}
void ui_event_ArcBrightnessLightStrip(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lightstripBrightness = lv_arc_get_value(ui_ArcBrightnessLightStrip);     
        lightstripBrightnessChanged = true;
    }
}

void ui_event_SwRGBLamp1ColorAndBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenColorPicker, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenColorPicker_screen_init);
        screenLastOnFocus = SCREENCOLORPICKER;
        PRESSEDSWITCH = SWRGBLAMP1COLORBRI;
    }
}
void ui_event_SwRGBLamp2ColorAndBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenColorPicker, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenColorPicker_screen_init);
        screenLastOnFocus = SCREENCOLORPICKER;
        PRESSEDSWITCH = SWRGBLAMP2COLORBRI;
    }
}
void ui_event_SwRGBLamp3ColorAndBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenColorPicker, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenColorPicker_screen_init);
        screenLastOnFocus = SCREENCOLORPICKER;
        PRESSEDSWITCH = SWRGBLAMP3COLORBRI;
    }
}
void ui_event_SwLightStripBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {                
        //startColorTempScreen = true;
        _ui_screen_change(&ui_ScreenColorTemp, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenColorTemp_screen_init);
        screenLastOnFocus = SCREENCOLORTEMP;
    }
}

void ui_event_BtnColorPickerDone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {        
        _ui_screen_change(&ui_ScreenLightControl, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenLightControl_screen_init);
        screenLastOnFocus = 2;  
        objectName = "rgbLamp1";  
    }      
}
void ui_event_BtnColorTempDone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenLightControl, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenLightControl_screen_init);
        screenLastOnFocus = 2;  
        objectName = "rgbLamp1";  
    }      
}
void ui_event_SwitchLightStripOnOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        if (!SwitchLightStripOnOff)
        {       
            PRESSEDSWITCH = SWLIGHTSTRIPON;  
            SwitchLightStripOnOff = true;
        }
        else
        {
            PRESSEDSWITCH = SWLIGHTSTRIPOFF; 
            SwitchLightStripOnOff = false;
        }        
    }
}
void ui_event_SwitchRGBLamp1OnOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        if (!SwitchRGBLamp1OnOff)
        {       
            PRESSEDSWITCH = SWRGBLAMP1ON;  
            SwitchRGBLamp1OnOff = true;
        }
        else
        {
            PRESSEDSWITCH = SWRGBLAMP1OFF;
            SwitchRGBLamp1OnOff = false;
        }
    }
}
void ui_event_SwitchRGBLamp2OnOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if (!SwitchRGBLamp2OnOff)
        {       
            PRESSEDSWITCH = SWRGBLAMP2ON;  
            SwitchRGBLamp2OnOff = true;
        }
        else
        {
            PRESSEDSWITCH = SWRGBLAMP2OFF;
            SwitchRGBLamp2OnOff = false;
        } 
    }
}
void ui_event_SwitchRGBLamp3OnOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if (!SwitchRGBLamp3OnOff)
        {       
            PRESSEDSWITCH = SWRGBLAMP3ON;  
            SwitchRGBLamp3OnOff = true;
        }
        else
        {
            PRESSEDSWITCH = SWRGBLAMP3OFF;
            SwitchRGBLamp3OnOff = false;
        } 
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_splash_screen_init();
    ui_ScreenWeather_screen_init();
    ui_ScreenLightControl_screen_init();
    ui_ScreenColorPicker_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_splash);
}
