// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"


//lv_coord_t series_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

void ui_Screen1_screen_init(void)
{
    //__chart1_series_array = series_array;
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart1, 673);
    lv_obj_set_height(ui_Chart1, 389);
    lv_obj_set_x(ui_Chart1, -3);
    lv_obj_set_y(ui_Chart1, 6);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_palette_main(LV_PALETTE_GREEN),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    //static lv_coord_t ui_Chart1_series_1_array[] = { 0, 5, 10, 15, 20, 25, 30, 35, 30, 20 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, data_Chart1_series_array);
    lv_chart_series_t * ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_palette_main(LV_PALETTE_RED),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    //static lv_coord_t ui_Chart1_series_2_array[] = { 2, 10, 20, 20, 30, 30, 20, 20, 10, 2 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, data_Chart2_series_array);
}
