// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSwitchBoard_screen_init(void)
{
    ui_ScreenSwitchBoard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitchBoard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch3 = lv_switch_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Switch3, 200);
    lv_obj_set_height(ui_Switch3, 100);
    lv_obj_set_x(ui_Switch3, -230);
    lv_obj_set_y(ui_Switch3, 150);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);


    ui_Switch1 = lv_switch_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Switch1, 200);
    lv_obj_set_height(ui_Switch1, 100);
    lv_obj_set_x(ui_Switch1, -230);
    lv_obj_set_y(ui_Switch1, -80);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Switch2 = lv_switch_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Switch2, 200);
    lv_obj_set_height(ui_Switch2, 100);
    lv_obj_set_x(ui_Switch2, 200);
    lv_obj_set_y(ui_Switch2, -80);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Switch4 = lv_switch_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Switch4, 200);
    lv_obj_set_height(ui_Switch4, 100);
    lv_obj_set_x(ui_Switch4, 200);
    lv_obj_set_y(ui_Switch4, 150);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);


    ui_Label1 = lv_label_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -250);
    lv_obj_set_y(ui_Label1, -170);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SWITCH 1");
    lv_obj_set_style_shadow_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -250);
    lv_obj_set_y(ui_Label2, 60);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SWITCH 3");

    ui_Label3 = lv_label_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 200);
    lv_obj_set_y(ui_Label3, -170);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SWITCH 2");

    ui_Label4 = lv_label_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 200);
    lv_obj_set_y(ui_Label4, 60);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SWITCH 4");

    ui_Label5 = lv_label_create(ui_ScreenSwitchBoard);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -20);
    lv_obj_set_y(ui_Label5, -220);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SWITCH BOARD");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label5, lv_color_hex(0x040C90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label5, lv_color_hex(0x323030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Label5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenSwitchBoard, ui_event_ScreenSwitchBoard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
 //   lv_obj_add_event_cb(ui_ScreenSwitchBoard, ui_event_ScreenSwitchBoard, LV_EVENT_ALL, NULL);

}
