// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWeather_screen_init(void)
{
    ui_ScreenWeather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenWeather, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenWeather, lv_color_hex(0xADC7E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenWeather, lv_color_hex(0xBCA5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenWeather, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNodeSelectWeather = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelNodeSelectWeather, 90);
    lv_obj_set_height(ui_PanelNodeSelectWeather, 430);
    lv_obj_set_x(ui_PanelNodeSelectWeather, 330);
    lv_obj_set_y(ui_PanelNodeSelectWeather, 0);
    lv_obj_set_align(ui_PanelNodeSelectWeather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNodeSelectWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNodeSelectWeather, lv_color_hex(0xADC7E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNodeSelectWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelNodeSelectWeather, lv_color_hex(0xBCA5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelNodeSelectWeather, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderWifiNodetWeather = lv_slider_create(ui_ScreenWeather);
    lv_slider_set_value(ui_SliderWifiNodetWeather, 95, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderWifiNodetWeather) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderWifiNodetWeather, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderWifiNodetWeather, 20);
    lv_obj_set_height(ui_SliderWifiNodetWeather, 340);
    lv_obj_set_x(ui_SliderWifiNodetWeather, 330);
    lv_obj_set_y(ui_SliderWifiNodetWeather, 10);
    lv_obj_set_align(ui_SliderWifiNodetWeather, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderWifiNodetWeather, lv_color_hex(0xADC7E3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifiNodetWeather, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderWifiNodetWeather, lv_color_hex(0xBCA5A5), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderWifiNodetWeather, lv_color_hex(0x6B5656), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifiNodetWeather, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderWifiNodetWeather, lv_color_hex(0x201717), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderWifiNodetWeather, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelHeadertWeather = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelHeadertWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeadertWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeadertWeather, 330);
    lv_obj_set_y(ui_LabelHeadertWeather, -192);
    lv_obj_set_align(ui_LabelHeadertWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeadertWeather, "NODE");
    lv_obj_set_style_text_font(ui_LabelHeadertWeather, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHeadertWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHeadertWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1Weather = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelNode1Weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode1Weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1Weather, 355);
    lv_obj_set_y(ui_LabelNode1Weather, -150);
    lv_obj_set_align(ui_LabelNode1Weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode1Weather, "- 1");
    lv_obj_set_style_text_font(ui_LabelNode1Weather, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode2Weather = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelNode2Weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode2Weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode2Weather, 355);
    lv_obj_set_y(ui_LabelNode2Weather, 10);
    lv_obj_set_align(ui_LabelNode2Weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode2Weather, "- 2");
    lv_obj_set_style_text_font(ui_LabelNode2Weather, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3Weather = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelNode3Weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode3Weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3Weather, 355);
    lv_obj_set_y(ui_LabelNode3Weather, 160);
    lv_obj_set_align(ui_LabelNode3Weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode3Weather, "- 3");
    lv_obj_set_style_text_font(ui_LabelNode3Weather, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMainHeaderWeather = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelMainHeaderWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMainHeaderWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMainHeaderWeather, -60);
    lv_obj_set_y(ui_LabelMainHeaderWeather, -200);
    lv_obj_set_align(ui_LabelMainHeaderWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainHeaderWeather, "CONTROL PANEL");
    lv_obj_set_style_text_letter_space(ui_LabelMainHeaderWeather, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMainHeaderWeather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMainHeaderWeather, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelMainHeaderWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelMainHeaderWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelMainHeaderWeather, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelMainHeaderWeather, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatusWeather = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelStatusWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatusWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatusWeather, -55);
    lv_obj_set_y(ui_LabelStatusWeather, 222);
    lv_obj_set_align(ui_LabelStatusWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatusWeather, "...");

    ui_PanelIndoorTemp = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelIndoorTemp, 300);
    lv_obj_set_height(ui_PanelIndoorTemp, 170);
    lv_obj_set_x(ui_PanelIndoorTemp, -215);
    lv_obj_set_y(ui_PanelIndoorTemp, -60);
    lv_obj_set_align(ui_PanelIndoorTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelIndoorTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelIndoorTemp, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelIndoorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelOutdoorTemp = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelOutdoorTemp, 300);
    lv_obj_set_height(ui_PanelOutdoorTemp, 170);
    lv_obj_set_x(ui_PanelOutdoorTemp, 100);
    lv_obj_set_y(ui_PanelOutdoorTemp, -60);
    lv_obj_set_align(ui_PanelOutdoorTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelOutdoorTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelOutdoorTemp, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelOutdoorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHumidity = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelHumidity, 300);
    lv_obj_set_height(ui_PanelHumidity, 170);
    lv_obj_set_x(ui_PanelHumidity, -215);
    lv_obj_set_y(ui_PanelHumidity, 120);
    lv_obj_set_align(ui_PanelHumidity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHumidity, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPressure = lv_obj_create(ui_ScreenWeather);
    lv_obj_set_width(ui_PanelPressure, 300);
    lv_obj_set_height(ui_PanelPressure, 170);
    lv_obj_set_x(ui_PanelPressure, 100);
    lv_obj_set_y(ui_PanelPressure, 120);
    lv_obj_set_align(ui_PanelPressure, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPressure, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIndoorTemp = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelIndoorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIndoorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIndoorTemp, -215);
    lv_obj_set_y(ui_LabelIndoorTemp, -58);
    lv_obj_set_align(ui_LabelIndoorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIndoorTemp, "00.0");
    lv_obj_set_style_text_color(ui_LabelIndoorTemp, lv_color_hex(0x800308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIndoorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIndoorTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOutdoorTemp = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelOutdoorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutdoorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOutdoorTemp, 100);
    lv_obj_set_y(ui_LabelOutdoorTemp, -58);
    lv_obj_set_align(ui_LabelOutdoorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOutdoorTemp, "00.0");
    lv_obj_set_style_text_color(ui_LabelOutdoorTemp, lv_color_hex(0x800308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutdoorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOutdoorTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidity = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidity, -215);
    lv_obj_set_y(ui_LabelHumidity, 117);
    lv_obj_set_align(ui_LabelHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidity, "00.0");
    lv_obj_set_style_text_color(ui_LabelHumidity, lv_color_hex(0x800308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumidity, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPressure = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelPressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPressure, 100);
    lv_obj_set_y(ui_LabelPressure, 117);
    lv_obj_set_align(ui_LabelPressure, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPressure, "00.0");
    lv_obj_set_style_text_color(ui_LabelPressure, lv_color_hex(0x800308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPressure, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIndoorTempUnit = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelIndoorTempUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIndoorTempUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIndoorTempUnit, -120);
    lv_obj_set_y(ui_LabelIndoorTempUnit, -58);
    lv_obj_set_align(ui_LabelIndoorTempUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIndoorTempUnit, "0°C");
    lv_obj_set_style_text_color(ui_LabelIndoorTempUnit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIndoorTempUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIndoorTempUnit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOutdoorTempUnit = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelOutdoorTempUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutdoorTempUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOutdoorTempUnit, 195);
    lv_obj_set_y(ui_LabelOutdoorTempUnit, -58);
    lv_obj_set_align(ui_LabelOutdoorTempUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOutdoorTempUnit, "0°C");
    lv_obj_set_style_text_color(ui_LabelOutdoorTempUnit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutdoorTempUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOutdoorTempUnit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidityUnit = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelHumidityUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumidityUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumidityUnit, -114);
    lv_obj_set_y(ui_LabelHumidityUnit, 117);
    lv_obj_set_align(ui_LabelHumidityUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidityUnit, "g/kg");
    lv_obj_set_style_text_color(ui_LabelHumidityUnit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumidityUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumidityUnit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPressureUnit = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LabelPressureUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPressureUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPressureUnit, 195);
    lv_obj_set_y(ui_LabelPressureUnit, 117);
    lv_obj_set_align(ui_LabelPressureUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPressureUnit, "hPa");
    lv_obj_set_style_text_color(ui_LabelPressureUnit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPressureUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPressureUnit, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_add_event_cb( ui_ButtonRelay1,	ui_event_ButtonRelay1, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_ButtonRelay2, 	ui_event_ButtonRelay2, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_ButtonRelay3, 	ui_event_ButtonRelay3, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_ButtonRelay4, 	ui_event_ButtonRelay4, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_SliderWifiNode, ui_event_SliderWifiNode,LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenSwitches, ui_event_ScreenWeather, LV_EVENT_ALL, NULL);

}
