// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenWeatherCharts_screen_init(void)
{
    ui_ScreenWeatherCharts = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWeatherCharts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenWeatherCharts, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenWeatherCharts, lv_color_hex(0xADC7E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWeatherCharts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenWeatherCharts, lv_color_hex(0xBCA5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenWeatherCharts, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNodeSelectWChart = lv_obj_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_PanelNodeSelectWChart, 90);
    lv_obj_set_height(ui_PanelNodeSelectWChart, 430);
    lv_obj_set_x(ui_PanelNodeSelectWChart, 330);
    lv_obj_set_y(ui_PanelNodeSelectWChart, 0);
    lv_obj_set_align(ui_PanelNodeSelectWChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNodeSelectWChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNodeSelectWChart, lv_color_hex(0xADC7E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNodeSelectWChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelNodeSelectWChart, lv_color_hex(0xBCA5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelNodeSelectWChart, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderWifiNodeWChart = lv_slider_create(ui_ScreenWeatherCharts);
    lv_slider_set_value(ui_SliderWifiNodeWChart, 95, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderWifiNodeWChart) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderWifiNodeWChart, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderWifiNodeWChart, 20);
    lv_obj_set_height(ui_SliderWifiNodeWChart, 340);
    lv_obj_set_x(ui_SliderWifiNodeWChart, 330);
    lv_obj_set_y(ui_SliderWifiNodeWChart, 10);
    lv_obj_set_align(ui_SliderWifiNodeWChart, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderWifiNodeWChart, lv_color_hex(0xADC7E3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifiNodeWChart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderWifiNodeWChart, lv_color_hex(0xBCA5A5), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderWifiNodeWChart, lv_color_hex(0x6B5656), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifiNodeWChart, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderWifiNodeWChart, lv_color_hex(0x201717), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderWifiNodeWChart, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelHeaderWChart = lv_label_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_LabelHeaderWChart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeaderWChart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeaderWChart, 330);
    lv_obj_set_y(ui_LabelHeaderWChart, -192);
    lv_obj_set_align(ui_LabelHeaderWChart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeaderWChart, "NODE");
    lv_obj_set_style_text_font(ui_LabelHeaderWChart, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHeaderWChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHeaderWChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1WChart = lv_label_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_LabelNode1WChart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode1WChart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1WChart, 355);
    lv_obj_set_y(ui_LabelNode1WChart, -150);
    lv_obj_set_align(ui_LabelNode1WChart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode1WChart, "- 1");
    lv_obj_set_style_text_font(ui_LabelNode1WChart, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode2WChart = lv_label_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_LabelNode2WChart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode2WChart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode2WChart, 355);
    lv_obj_set_y(ui_LabelNode2WChart, 10);
    lv_obj_set_align(ui_LabelNode2WChart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode2WChart, "- 2");
    lv_obj_set_style_text_font(ui_LabelNode2WChart, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3WChart = lv_label_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_LabelNode3WChart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode3WChart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3WChart, 355);
    lv_obj_set_y(ui_LabelNode3WChart, 160);
    lv_obj_set_align(ui_LabelNode3WChart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode3WChart, "- 3");
    lv_obj_set_style_text_font(ui_LabelNode3WChart, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMainHeaderWChart = lv_label_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_LabelMainHeaderWChart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMainHeaderWChart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMainHeaderWChart, -60);
    lv_obj_set_y(ui_LabelMainHeaderWChart, -200);
    lv_obj_set_align(ui_LabelMainHeaderWChart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainHeaderWChart, "CONTROL PANEL");
    lv_obj_set_style_text_letter_space(ui_LabelMainHeaderWChart, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMainHeaderWChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMainHeaderWChart, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelMainHeaderWChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelMainHeaderWChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelMainHeaderWChart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelMainHeaderWChart, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatusWChart = lv_label_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_LabelStatusWChart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatusWChart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatusWChart, -55);
    lv_obj_set_y(ui_LabelStatusWChart, 222);
    lv_obj_set_align(ui_LabelStatusWChart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatusWChart, "...");

    ui_PanelIndoorTempWChart = lv_obj_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_PanelIndoorTempWChart, 300);
    lv_obj_set_height(ui_PanelIndoorTempWChart, 170);
    lv_obj_set_x(ui_PanelIndoorTempWChart, -215);
    lv_obj_set_y(ui_PanelIndoorTempWChart, -60);
    lv_obj_set_align(ui_PanelIndoorTempWChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelIndoorTempWChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelIndoorTempWChart, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelIndoorTempWChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartIndoorTemp = lv_chart_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_ChartIndoorTemp, 250);
    lv_obj_set_height(ui_ChartIndoorTemp, 120);
    lv_obj_set_x(ui_ChartIndoorTemp, -200);
    lv_obj_set_y(ui_ChartIndoorTemp, -70);
    lv_obj_set_align(ui_ChartIndoorTemp, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartIndoorTemp, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ChartIndoorTemp, LV_CHART_AXIS_PRIMARY_Y, -10, 100);
    lv_chart_set_range(ui_ChartIndoorTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartIndoorTemp, 10, 10);
    lv_chart_set_axis_tick(ui_ChartIndoorTemp, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartIndoorTemp, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 20);
    lv_chart_set_axis_tick(ui_ChartIndoorTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_chart_series_t * ui_ChartIndoorTemp_series_1 = lv_chart_add_series(ui_ChartIndoorTemp, lv_color_hex(0x960303),
                                                                          LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartIndoorTemp_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartIndoorTemp, ui_ChartIndoorTemp_series_1, ui_ChartIndoorTemp_series_1_array);



    ui_PanelOutdoorTempWChart = lv_obj_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_PanelOutdoorTempWChart, 300);
    lv_obj_set_height(ui_PanelOutdoorTempWChart, 170);
    lv_obj_set_x(ui_PanelOutdoorTempWChart, 100);
    lv_obj_set_y(ui_PanelOutdoorTempWChart, -60);
    lv_obj_set_align(ui_PanelOutdoorTempWChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelOutdoorTempWChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelOutdoorTempWChart, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelOutdoorTempWChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartOutdoorTemp = lv_chart_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_ChartOutdoorTemp, 250);
    lv_obj_set_height(ui_ChartOutdoorTemp, 120);
    lv_obj_set_x(ui_ChartOutdoorTemp, 115);
    lv_obj_set_y(ui_ChartOutdoorTemp, -70);
    lv_obj_set_align(ui_ChartOutdoorTemp, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartOutdoorTemp, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ChartOutdoorTemp, LV_CHART_AXIS_PRIMARY_Y, -10, 100);
    lv_chart_set_range(ui_ChartOutdoorTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartOutdoorTemp, 10, 10);
    lv_chart_set_axis_tick(ui_ChartOutdoorTemp, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartOutdoorTemp, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 20);
    lv_chart_set_axis_tick(ui_ChartOutdoorTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_chart_series_t * ui_ChartOutdoorTemp_series_1 = lv_chart_add_series(ui_ChartOutdoorTemp, lv_color_hex(0x960303),
                                                                           LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartOutdoorTemp_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartOutdoorTemp, ui_ChartOutdoorTemp_series_1, ui_ChartOutdoorTemp_series_1_array);



    ui_PanelHumidityWChart = lv_obj_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_PanelHumidityWChart, 300);
    lv_obj_set_height(ui_PanelHumidityWChart, 170);
    lv_obj_set_x(ui_PanelHumidityWChart, -215);
    lv_obj_set_y(ui_PanelHumidityWChart, 120);
    lv_obj_set_align(ui_PanelHumidityWChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHumidityWChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHumidityWChart, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHumidityWChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartHumidity = lv_chart_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_ChartHumidity, 250);
    lv_obj_set_height(ui_ChartHumidity, 120);
    lv_obj_set_x(ui_ChartHumidity, -200);
    lv_obj_set_y(ui_ChartHumidity, 110);
    lv_obj_set_align(ui_ChartHumidity, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartHumidity, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ChartHumidity, LV_CHART_AXIS_PRIMARY_Y, -10, 100);
    lv_chart_set_range(ui_ChartHumidity, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartHumidity, 10, 10);
    lv_chart_set_axis_tick(ui_ChartHumidity, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartHumidity, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 20);
    lv_chart_set_axis_tick(ui_ChartHumidity, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_chart_series_t * ui_ChartHumidity_series_1 = lv_chart_add_series(ui_ChartHumidity, lv_color_hex(0x960303),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartHumidity_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartHumidity, ui_ChartHumidity_series_1, ui_ChartHumidity_series_1_array);



    ui_PanelPressureWChart = lv_obj_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_PanelPressureWChart, 300);
    lv_obj_set_height(ui_PanelPressureWChart, 170);
    lv_obj_set_x(ui_PanelPressureWChart, 100);
    lv_obj_set_y(ui_PanelPressureWChart, 120);
    lv_obj_set_align(ui_PanelPressureWChart, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPressureWChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPressureWChart, lv_color_hex(0x5E99FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPressureWChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartPressure = lv_chart_create(ui_ScreenWeatherCharts);
    lv_obj_set_width(ui_ChartPressure, 250);
    lv_obj_set_height(ui_ChartPressure, 120);
    lv_obj_set_x(ui_ChartPressure, 115);
    lv_obj_set_y(ui_ChartPressure, 110);
    lv_obj_set_align(ui_ChartPressure, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartPressure, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_ChartPressure, LV_CHART_AXIS_PRIMARY_Y, -10, 100);
    lv_chart_set_range(ui_ChartPressure, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartPressure, 10, 10);
    lv_chart_set_axis_tick(ui_ChartPressure, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartPressure, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 20);
    lv_chart_set_axis_tick(ui_ChartPressure, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_chart_series_t * ui_ChartPressure_series_1 = lv_chart_add_series(ui_ChartPressure, lv_color_hex(0x960303),
                                                                        LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartPressure_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_ChartPressure, ui_ChartPressure_series_1, ui_ChartPressure_series_1_array);



    lv_obj_add_event_cb(ui_ScreenWeatherCharts, ui_event_ScreenWeatherCharts, LV_EVENT_ALL, NULL);

}
