// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenSwitches_screen_init(void)
{
    ui_ScreenSwitches = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitches, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenSwitches, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenSwitches, lv_color_hex(0xADC7E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitches, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenSwitches, lv_color_hex(0xBCA5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenSwitches, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNodeSelect = lv_obj_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_PanelNodeSelect, 90);
    lv_obj_set_height(ui_PanelNodeSelect, 430);
    lv_obj_set_x(ui_PanelNodeSelect, 330);
    lv_obj_set_y(ui_PanelNodeSelect, 0);
    lv_obj_set_align(ui_PanelNodeSelect, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelNodeSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNodeSelect, lv_color_hex(0xADC7E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNodeSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PanelNodeSelect, lv_color_hex(0xBCA5A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PanelNodeSelect, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderWifiNode = lv_slider_create(ui_ScreenSwitches);
    lv_slider_set_value(ui_SliderWifiNode, 95, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderWifiNode) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderWifiNode, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderWifiNode, 20);
    lv_obj_set_height(ui_SliderWifiNode, 340);
    lv_obj_set_x(ui_SliderWifiNode, 330);
    lv_obj_set_y(ui_SliderWifiNode, 10);
    lv_obj_set_align(ui_SliderWifiNode, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_SliderWifiNode, lv_color_hex(0xADC7E3), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifiNode, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderWifiNode, lv_color_hex(0xBCA5A5), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderWifiNode, lv_color_hex(0x6B5656), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderWifiNode, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderWifiNode, lv_color_hex(0x201717), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderWifiNode, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelHeader = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeader, 330);
    lv_obj_set_y(ui_LabelHeader, -192);
    lv_obj_set_align(ui_LabelHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeader, "NODE");
    lv_obj_set_style_text_font(ui_LabelHeader, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode1 = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelNode1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode1, 355);
    lv_obj_set_y(ui_LabelNode1, -150);
    lv_obj_set_align(ui_LabelNode1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode1, "- 1");
    lv_obj_set_style_text_font(ui_LabelNode1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode2 = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelNode2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode2, 355);
    lv_obj_set_y(ui_LabelNode2, 10);
    lv_obj_set_align(ui_LabelNode2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode2, "- 2");
    lv_obj_set_style_text_font(ui_LabelNode2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNode3 = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelNode3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNode3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNode3, 355);
    lv_obj_set_y(ui_LabelNode3, 160);
    lv_obj_set_align(ui_LabelNode3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNode3, "- 3");
    lv_obj_set_style_text_font(ui_LabelNode3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRelay1 = lv_btn_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_ButtonRelay1, 250);
    lv_obj_set_height(ui_ButtonRelay1, 150);
    lv_obj_set_x(ui_ButtonRelay1, -210);
    lv_obj_set_y(ui_ButtonRelay1, -70);
    lv_obj_set_align(ui_ButtonRelay1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRelay1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRelay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRelay1, lv_color_hex(0x6B5656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRelay1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonRelay1, lv_color_hex(0x201717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonRelay1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRelay2 = lv_btn_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_ButtonRelay2, 250);
    lv_obj_set_height(ui_ButtonRelay2, 150);
    lv_obj_set_x(ui_ButtonRelay2, 100);
    lv_obj_set_y(ui_ButtonRelay2, -70);
    lv_obj_set_align(ui_ButtonRelay2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRelay2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRelay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRelay2, lv_color_hex(0x6B5656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRelay2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonRelay2, lv_color_hex(0x201717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonRelay2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRelay3 = lv_btn_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_ButtonRelay3, 250);
    lv_obj_set_height(ui_ButtonRelay3, 150);
    lv_obj_set_x(ui_ButtonRelay3, -210);
    lv_obj_set_y(ui_ButtonRelay3, 120);
    lv_obj_set_align(ui_ButtonRelay3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRelay3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRelay3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRelay3, lv_color_hex(0x6B5656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRelay3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonRelay3, lv_color_hex(0x201717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonRelay3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRelay4 = lv_btn_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_ButtonRelay4, 250);
    lv_obj_set_height(ui_ButtonRelay4, 150);
    lv_obj_set_x(ui_ButtonRelay4, 100);
    lv_obj_set_y(ui_ButtonRelay4, 120);
    lv_obj_set_align(ui_ButtonRelay4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRelay4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRelay4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRelay4, lv_color_hex(0x6B5656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRelay4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonRelay4, lv_color_hex(0x201717), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonRelay4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMainHeader = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelMainHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMainHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMainHeader, -60);
    lv_obj_set_y(ui_LabelMainHeader, -200);
    lv_obj_set_align(ui_LabelMainHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainHeader, "CONTROL PANEL");
    lv_obj_set_style_text_letter_space(ui_LabelMainHeader, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMainHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMainHeader, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelMainHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelMainHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LabelMainHeader, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LabelMainHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnRelay1 = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelBtnRelay1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnRelay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnRelay1, -210);
    lv_obj_set_y(ui_LabelBtnRelay1, -70);
    lv_obj_set_align(ui_LabelBtnRelay1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnRelay1, "OFF");
    lv_obj_set_style_text_color(ui_LabelBtnRelay1, lv_color_hex(0xC40303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnRelay1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnRelay1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnRelay2 = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelBtnRelay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnRelay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnRelay2, 100);
    lv_obj_set_y(ui_LabelBtnRelay2, -70);
    lv_obj_set_align(ui_LabelBtnRelay2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnRelay2, "OFF");
    lv_obj_set_style_text_color(ui_LabelBtnRelay2, lv_color_hex(0xC40303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnRelay2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnRelay2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnRelay3 = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelBtnRelay3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnRelay3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnRelay3, -210);
    lv_obj_set_y(ui_LabelBtnRelay3, 120);
    lv_obj_set_align(ui_LabelBtnRelay3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnRelay3, "OFF");
    lv_obj_set_style_text_color(ui_LabelBtnRelay3, lv_color_hex(0xC40303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnRelay3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnRelay3, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnRelay4 = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelBtnRelay4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnRelay4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnRelay4, 100);
    lv_obj_set_y(ui_LabelBtnRelay4, 120);
    lv_obj_set_align(ui_LabelBtnRelay4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnRelay4, "OFF");
    lv_obj_set_style_text_color(ui_LabelBtnRelay4, lv_color_hex(0xC40303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnRelay4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnRelay4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatus = lv_label_create(ui_ScreenSwitches);
    lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatus, -55);
    lv_obj_set_y(ui_LabelStatus, 222);
    lv_obj_set_align(ui_LabelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatus, "...");

    lv_obj_add_event_cb(ui_ScreenSwitches, ui_event_ScreenSwitches, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_ButtonRelay1,	ui_event_ButtonRelay1, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_ButtonRelay2, 	ui_event_ButtonRelay2, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_ButtonRelay3, 	ui_event_ButtonRelay3, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_ButtonRelay4, 	ui_event_ButtonRelay4, 	LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb( ui_SliderWifiNode, ui_event_SliderWifiNode,LV_EVENT_ALL, NULL);

}
