// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_splash
void ui_splash_screen_init(void);
void ui_event_splash(lv_event_t * e);
extern lv_obj_t * ui_splash;
// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
void ui_event_BtnSc1Left(lv_event_t * e);
void ui_event_BtnSc1Right(lv_event_t * e);
extern lv_obj_t * ui_ScreenWeather;
extern lv_obj_t * ui_WeatherHeader;
extern lv_obj_t * ui_WeatherHeader1;
extern lv_obj_t * ui_iconWeather;
extern lv_obj_t * ui_iconTemp;
extern lv_obj_t * ui_iconAirPressure;
extern lv_obj_t * ui_iconAirHumidity;
extern lv_obj_t * ui_iconWindSpeed;
extern lv_obj_t * ui_ContainerWeatherForcast;
extern lv_obj_t * ui_LbTempText1;
extern lv_obj_t * ui_LbPressureText1;
extern lv_obj_t * ui_LbHumidityText1;
extern lv_obj_t * ui_LbWindspeedText1;
extern lv_obj_t * ui_LbTempValue1;
extern lv_obj_t * ui_LbPressureValue1;
extern lv_obj_t * ui_LbHumidityValue1;
extern lv_obj_t * ui_LbWindspeedValue1;
extern lv_obj_t * ui_LbTempUnit1;
extern lv_obj_t * ui_LbPressureUnit1;
extern lv_obj_t * ui_LbHumidityUnit1;
extern lv_obj_t * ui_LbWindspeedUnit1;
extern lv_obj_t * ui_ContainerIndoorTemp;
extern lv_obj_t * ui_LbTempText2;
extern lv_obj_t * ui_LbPressureText2;
extern lv_obj_t * ui_LbHumidityText2;
extern lv_obj_t * ui_LbWindspeedText2;
extern lv_obj_t * ui_LbTempValue2;
extern lv_obj_t * ui_LbPressureValue2;
extern lv_obj_t * ui_LbHumidityValue2;
extern lv_obj_t * ui_LbWindspeedValue2;
extern lv_obj_t * ui_LbTempUnit2;
extern lv_obj_t * ui_LbPressureUnit2;
extern lv_obj_t * ui_LbHumidityUnit2;
extern lv_obj_t * ui_LbWindspeedUnit2;
extern lv_obj_t * ui_BtnSc1Left;
extern lv_obj_t * ui_BtnSc1Right;
extern lv_obj_t * ui_lbSc1LoadStatus;
extern lv_obj_t * ui_BtnSc1Left;
extern lv_obj_t * ui_BtnSc1Right; 
extern lv_obj_t * ui_LbTimeAndDate;

void ui_ScreenSwitchNode1_screen_init(void);
void ui_event_Switch1Node1(lv_event_t * e);
void ui_event_Switch2Node1(lv_event_t * e);
void ui_event_Switch3Node1(lv_event_t * e);
void ui_event_Switch4Node1(lv_event_t * e);
void ui_event_BtnSc2Left(lv_event_t * e);
void ui_event_BtnSc2Right(lv_event_t * e);
extern lv_obj_t * ui_LabelHeaderNode1;
extern lv_obj_t * ui_ScreenSwitchNode1;
extern lv_obj_t * ui_PanelSwitch1Node1;
extern lv_obj_t * ui_PanelSwitch2Node1;
extern lv_obj_t * ui_PanelSwitch3Node1;
extern lv_obj_t * ui_PanelSwitch4Node1;
extern lv_obj_t * ui_Switch1Node1;
extern lv_obj_t * ui_Switch2Node1;
extern lv_obj_t * ui_Switch3Node1;
extern lv_obj_t * ui_Switch4Node1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_BtnSc2Left;
extern lv_obj_t * ui_BtnSc2Right;
extern lv_obj_t * ui_lbSc2LoadStatus;
extern lv_obj_t * ui_LbSwitch1Node1;
extern lv_obj_t * ui_LbSwitch2Node1;
extern lv_obj_t * ui_LbSwitch3Node1;
extern lv_obj_t * ui_LbSwitch4Node1;

void ui_ScreenSwitchNode2_screen_init(void);
void ui_event_Switch1Node2(lv_event_t * e);
void ui_event_Switch2Node2(lv_event_t * e);
void ui_event_Switch3Node2(lv_event_t * e);
void ui_event_Switch4Node2(lv_event_t * e);
void ui_event_BtnSc3Left(lv_event_t * e);
void ui_event_BtnSc3Right(lv_event_t * e);
extern lv_obj_t * ui_LabelHeaderNode2;
extern lv_obj_t * ui_ScreenSwitchNode2;
extern lv_obj_t * ui_PanelSwitch1Node2;
extern lv_obj_t * ui_PanelSwitch2Node2;
extern lv_obj_t * ui_PanelSwitch3Node2;
extern lv_obj_t * ui_PanelSwitch4Node2;
extern lv_obj_t * ui_Switch1Node2;
extern lv_obj_t * ui_Switch2Node2;
extern lv_obj_t * ui_Switch3Node2;
extern lv_obj_t * ui_Switch4Node2;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_BtnSc3Left;
extern lv_obj_t * ui_BtnSc3Right;
extern lv_obj_t * ui_lbSc3LoadStatus;
extern lv_obj_t * ui_LbSwitch1Node2;
extern lv_obj_t * ui_LbSwitch2Node2;
extern lv_obj_t * ui_LbSwitch3Node2;
extern lv_obj_t * ui_LbSwitch4Node2;

// CUSTOM VARIABLES
extern lv_obj_t * uic_Image1;
// EVENTS
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo4b_png);    // assets/logo4b.png
// LV_IMG_DECLARE(ui_img_pattern1b1_png);    // assets/pattern1b1.png
LV_IMG_DECLARE(ui_img_arrow3_r_png);    // assets/pattern1b1.png
LV_IMG_DECLARE(ui_img_arrow3_l_png);    // assets/pattern1b1.png

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_999054828);    // assets/icons8-partly-cloudy-day-50.png
LV_IMG_DECLARE(ui_img_1578496546);    // assets/icons8-thermometer-50.png
LV_IMG_DECLARE(ui_img_1668089981);    // assets/icons8-pressure-gauge-50.png
LV_IMG_DECLARE(ui_img_947629812);    // assets/icons8-hygrometer-50.png
LV_IMG_DECLARE(ui_img_233333594);    // assets/icons8-air-50.png
LV_IMG_DECLARE(ui_img_blue_background_5_png);    // assets/blue_background_5.png
LV_IMG_DECLARE(ui_img_pattern1b1_png);    // assets/pattern1b1.png
// FONTS
LV_FONT_DECLARE(ui_font_NumberDotsFont);
LV_FONT_DECLARE(ui_font_NumberDotsFont30);
LV_FONT_DECLARE(ui_font_NumbersDigital);
LV_FONT_DECLARE(ui_font_NumbersDigital60);
LV_FONT_DECLARE(ui_font_AnandaBlack);
LV_FONT_DECLARE(ui_font_AnandaBlack40);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
