// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenSwitch1_screen_init(void)
{
    ui_ScreenSwitch1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitch1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSwitch1, lv_color_hex(0x467493), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenSwitch1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbHeaderSwitch1 = lv_label_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_lbHeaderSwitch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbHeaderSwitch1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbHeaderSwitch1, -1);
    lv_obj_set_y(ui_lbHeaderSwitch1, -360);
    lv_obj_set_align(ui_lbHeaderSwitch1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbHeaderSwitch1, "    Switch 1    ");
    lv_obj_set_style_text_color(ui_lbHeaderSwitch1, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbHeaderSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_lbHeaderSwitch1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_lbHeaderSwitch1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbHeaderSwitch1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lbHeaderSwitch1, lv_color_hex(0x444649), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lbHeaderSwitch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lbHeaderSwitch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lbHeaderSwitch1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lbHeaderSwitch1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1a = lv_switch_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_Switch1a, 164);
    lv_obj_set_height(ui_Switch1a, 108);
    lv_obj_set_x(ui_Switch1a, -120);
    lv_obj_set_y(ui_Switch1a, -170);
    lv_obj_set_align(ui_Switch1a, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1a, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1a, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch1b = lv_switch_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_Switch1b, 164);
    lv_obj_set_height(ui_Switch1b, 108);
    lv_obj_set_x(ui_Switch1b, 120);
    lv_obj_set_y(ui_Switch1b, -170);
    lv_obj_set_align(ui_Switch1b, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1b, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1b, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch1c = lv_switch_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_Switch1c, 164);
    lv_obj_set_height(ui_Switch1c, 108);
    lv_obj_set_x(ui_Switch1c, -120);
    lv_obj_set_y(ui_Switch1c, 30);
    lv_obj_set_align(ui_Switch1c, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1c, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1c, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch1d = lv_switch_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_Switch1d, 164);
    lv_obj_set_height(ui_Switch1d, 108);
    lv_obj_set_x(ui_Switch1d, 120);
    lv_obj_set_y(ui_Switch1d, 21);
    lv_obj_set_align(ui_Switch1d, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1d, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1d, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch1e = lv_switch_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_Switch1e, 164);
    lv_obj_set_height(ui_Switch1e, 108);
    lv_obj_set_x(ui_Switch1e, -120);
    lv_obj_set_y(ui_Switch1e, 200);
    lv_obj_set_align(ui_Switch1e, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1e, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1e, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch1f = lv_switch_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_Switch1f, 164);
    lv_obj_set_height(ui_Switch1f, 108);
    lv_obj_set_x(ui_Switch1f, 120);
    lv_obj_set_y(ui_Switch1f, 200);
    lv_obj_set_align(ui_Switch1f, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1f, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1f, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_lbConnectionSwitch1 = lv_label_create(ui_ScreenSwitch1);
    lv_obj_set_width(ui_lbConnectionSwitch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConnectionSwitch1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConnectionSwitch1, 0);
    lv_obj_set_y(ui_lbConnectionSwitch1, 340);
    lv_obj_set_align(ui_lbConnectionSwitch1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConnectionSwitch1, "connection");
	
	// lv_obj_add_event_cb(ui_ScreenSwitch1, ui_event_ui_ScreenSwitch1, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch1a,	ui_event_ui_Switch1a, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch1b, 	ui_event_ui_Switch1b, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch1c, 	ui_event_ui_Switch1c, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch1d, 	ui_event_ui_Switch1d, 	LV_EVENT_ALL, NULL);
}
