// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenSwitch2_screen_init(void)
{
    ui_ScreenSwitch2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSwitch2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSwitch2, lv_color_hex(0x467493), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenSwitch2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbHeaderSwitch2 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_lbHeaderSwitch2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbHeaderSwitch2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbHeaderSwitch2, -1);
    lv_obj_set_y(ui_lbHeaderSwitch2, -360);
    lv_obj_set_align(ui_lbHeaderSwitch2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbHeaderSwitch2, "    Switch 2    ");
    lv_obj_set_style_text_color(ui_lbHeaderSwitch2, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbHeaderSwitch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_lbHeaderSwitch2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_lbHeaderSwitch2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbHeaderSwitch2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lbHeaderSwitch2, lv_color_hex(0x444649), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lbHeaderSwitch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lbHeaderSwitch2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_lbHeaderSwitch2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_lbHeaderSwitch2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2a = lv_switch_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_Switch2a, 164);
    lv_obj_set_height(ui_Switch2a, 108);
    lv_obj_set_x(ui_Switch2a, -120);
    lv_obj_set_y(ui_Switch2a, -170);
    lv_obj_set_align(ui_Switch2a, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2a, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2a, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch2b = lv_switch_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_Switch2b, 164);
    lv_obj_set_height(ui_Switch2b, 108);
    lv_obj_set_x(ui_Switch2b, 120);
    lv_obj_set_y(ui_Switch2b, -170);
    lv_obj_set_align(ui_Switch2b, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2b, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2b, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch2c = lv_switch_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_Switch2c, 164);
    lv_obj_set_height(ui_Switch2c, 108);
    lv_obj_set_x(ui_Switch2c, -120);
    lv_obj_set_y(ui_Switch2c, 30);
    lv_obj_set_align(ui_Switch2c, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2c, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2c, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch2d = lv_switch_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_Switch2d, 164);
    lv_obj_set_height(ui_Switch2d, 108);
    lv_obj_set_x(ui_Switch2d, 120);
    lv_obj_set_y(ui_Switch2d, 21);
    lv_obj_set_align(ui_Switch2d, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2d, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2d, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch2e = lv_switch_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_Switch2e, 164);
    lv_obj_set_height(ui_Switch2e, 108);
    lv_obj_set_x(ui_Switch2e, -120);
    lv_obj_set_y(ui_Switch2e, 200);
    lv_obj_set_align(ui_Switch2e, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2e, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2e, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Switch2f = lv_switch_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_Switch2f, 164);
    lv_obj_set_height(ui_Switch2f, 108);
    lv_obj_set_x(ui_Switch2f, 120);
    lv_obj_set_y(ui_Switch2f, 200);
    lv_obj_set_align(ui_Switch2f, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2f, lv_color_hex(0xE80926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2f, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_lbConnectionSwitch2 = lv_label_create(ui_ScreenSwitch2);
    lv_obj_set_width(ui_lbConnectionSwitch2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbConnectionSwitch2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbConnectionSwitch2, 0);
    lv_obj_set_y(ui_lbConnectionSwitch2, 340);
    lv_obj_set_align(ui_lbConnectionSwitch2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbConnectionSwitch2, "connection");
	
	// lv_obj_add_event_cb(ui_ScreenSwitch1, ui_event_ui_ScreenSwitch1, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch2a,	ui_event_ui_Switch2a, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch2b, 	ui_event_ui_Switch2b, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch2c, 	ui_event_ui_Switch2c, 	LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb( ui_Switch2d, 	ui_event_ui_Switch2d, 	LV_EVENT_ALL, NULL);
}
