// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScreenSwitches
void ui_ScreenSwitches_screen_init(void);
void ui_event_ScreenSwitches(lv_event_t * e);
extern lv_obj_t * ui_ScreenSwitches;
extern lv_obj_t * ui_PanelNodeSelect;
extern lv_obj_t * ui_SliderWifiNode;
extern lv_obj_t * ui_LabelHeader;
extern lv_obj_t * ui_LabelNode1;
extern lv_obj_t * ui_LabelNode2;
extern lv_obj_t * ui_LabelNode3;
void ui_event_ButtonRelay1(lv_event_t * e);
void ui_event_ButtonRelay2(lv_event_t * e);
void ui_event_ButtonRelay3(lv_event_t * e);
void ui_event_ButtonRelay4(lv_event_t * e);
void ui_event_SliderWifiNode(lv_event_t * e);
extern lv_obj_t * ui_ButtonRelay1;
extern lv_obj_t * ui_ButtonRelay2;
extern lv_obj_t * ui_ButtonRelay3;
extern lv_obj_t * ui_ButtonRelay4;
extern lv_obj_t * ui_LabelMainHeader;
extern lv_obj_t * ui_LabelBtnRelay1;
extern lv_obj_t * ui_LabelBtnRelay2;
extern lv_obj_t * ui_LabelBtnRelay3;
extern lv_obj_t * ui_LabelBtnRelay4;
extern lv_obj_t * ui_LabelStatus;
// SCREEN: ui_ScreenWeather
void ui_ScreenWeather_screen_init(void);
void ui_event_ScreenWeather(lv_event_t * e);
extern lv_obj_t * ui_ScreenWeather;
extern lv_obj_t * ui_PanelNodeSelectWeather;
extern lv_obj_t * ui_SliderWifiNodetWeather;
extern lv_obj_t * ui_LabelHeadertWeather;
extern lv_obj_t * ui_LabelNode1Weather;
extern lv_obj_t * ui_LabelNode2Weather;
extern lv_obj_t * ui_LabelNode3Weather;
extern lv_obj_t * ui_LabelMainHeaderWeather;
extern lv_obj_t * ui_LabelStatusWeather;
extern lv_obj_t * ui_PanelIndoorTemp;
extern lv_obj_t * ui_PanelOutdoorTemp;
extern lv_obj_t * ui_PanelHumidity;
extern lv_obj_t * ui_PanelPressure;
extern lv_obj_t * ui_LabelIndoorTemp;
extern lv_obj_t * ui_LabelOutdoorTemp;
extern lv_obj_t * ui_LabelHumidity;
extern lv_obj_t * ui_LabelPressure;
extern lv_obj_t * ui_LabelIndoorTempUnit;
extern lv_obj_t * ui_LabelOutdoorTempUnit;
extern lv_obj_t * ui_LabelHumidityUnit;
extern lv_obj_t * ui_LabelPressureUnit;
// SCREEN: ui_ScreenWeatherCharts
void ui_ScreenWeatherCharts_screen_init(void);
void ui_event_ScreenWeatherCharts(lv_event_t * e);
extern lv_obj_t * ui_ScreenWeatherCharts;
extern lv_obj_t * ui_PanelNodeSelectWChart;
extern lv_obj_t * ui_SliderWifiNodeWChart;
extern lv_obj_t * ui_LabelHeaderWChart;
extern lv_obj_t * ui_LabelNode1WChart;
extern lv_obj_t * ui_LabelNode2WChart;
extern lv_obj_t * ui_LabelNode3WChart;
extern lv_obj_t * ui_LabelMainHeaderWChart;
extern lv_obj_t * ui_LabelStatusWChart;
extern lv_obj_t * ui_PanelIndoorTempWChart;
extern lv_obj_t * ui_ChartIndoorTemp;
extern lv_obj_t * ui_PanelOutdoorTempWChart;
extern lv_obj_t * ui_ChartOutdoorTemp;
extern lv_obj_t * ui_PanelHumidityWChart;
extern lv_obj_t * ui_ChartHumidity;
extern lv_obj_t * ui_PanelPressureWChart;
extern lv_obj_t * ui_ChartPressure;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_fire3_png);    // assets/fire3.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
