// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void upanim_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Demo;
extern lv_obj_t * ui_Smart_Gadget;
extern lv_obj_t * ui_SLS_Logo;
// SCREEN: ui_Clock
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Clock_Panel;
extern lv_obj_t * ui_Dot1;
extern lv_obj_t * ui_Dot2;
extern lv_obj_t * ui_Dot3;
extern lv_obj_t * ui_Dot4;
extern lv_obj_t * ui_Dot5;
extern lv_obj_t * ui_Dot6;
extern lv_obj_t * ui_Dot7;
extern lv_obj_t * ui_Dot8;
extern lv_obj_t * ui_Clock_Number1;
extern lv_obj_t * ui_Clock_Number2;
extern lv_obj_t * ui_Clock_Number3;
extern lv_obj_t * ui_Clock_Number4;
extern lv_obj_t * ui_Min;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Sec;
extern lv_obj_t * ui_Clock_Center;
extern lv_obj_t * ui_Clock_Number;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Scrolldots;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png
LV_IMG_DECLARE(ui_img_pattern1b1_png);    // assets/pattern1b1.png
LV_IMG_DECLARE(ui_img_clock_min_png);    // assets/clock_min.png
LV_IMG_DECLARE(ui_img_clock_hour_png);    // assets/clock_hour.png
LV_IMG_DECLARE(ui_img_clock_sec_png);    // assets/clock_sec.png
// LV_IMG_DECLARE(ui_img_chatbox2_png);    // assets/chatbox2.png
// LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
// LV_IMG_DECLARE(ui_img_weather_2_png);    // assets/weather_2.png
// LV_IMG_DECLARE(ui_img_weather_3_png);    // assets/weather_3.png



LV_FONT_DECLARE(ui_font_Number);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
