// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenColorPicker_screen_init(void)
{
    ui_ScreenColorPicker = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenColorPicker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenColorPicker, lv_color_hex(0x06374B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenColorPicker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnColorPickerDone = lv_btn_create(ui_ScreenColorPicker);
    lv_obj_set_width(ui_BtnColorPickerDone, 136);
    lv_obj_set_height(ui_BtnColorPickerDone, 48);
    lv_obj_set_x(ui_BtnColorPickerDone, 0);
    lv_obj_set_y(ui_BtnColorPickerDone, 200);
    lv_obj_set_align(ui_BtnColorPickerDone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnColorPickerDone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnColorPickerDone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_BtnColorPickerDone, lv_color_hex(0xB1A7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BtnColorPickerDone, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbColorPickerBtnText = lv_label_create(ui_BtnColorPickerDone);
    lv_obj_set_width(ui_LbColorPickerBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbColorPickerBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbColorPickerBtnText, -1);
    lv_obj_set_y(ui_LbColorPickerBtnText, -1);
    lv_obj_set_align(ui_LbColorPickerBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbColorPickerBtnText, "DONE");
    lv_obj_set_style_text_color(ui_LbColorPickerBtnText, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbColorPickerBtnText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbColorPickerBtnText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelColorPicker = lv_obj_create(ui_ScreenColorPicker);
    lv_obj_set_width(ui_PanelColorPicker, 752);
    lv_obj_set_height(ui_PanelColorPicker, 336);
    lv_obj_set_align(ui_PanelColorPicker, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelColorPicker, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelColorPicker, lv_color_hex(0x3D3939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelColorPicker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbColorPicker = lv_label_create(ui_ScreenColorPicker);
    lv_obj_set_width(ui_LbColorPicker, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbColorPicker, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbColorPicker, 0);
    lv_obj_set_y(ui_LbColorPicker, -200);
    lv_obj_set_align(ui_LbColorPicker, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbColorPicker, "COLOR PICKER");
    lv_obj_set_style_text_color(ui_LbColorPicker, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbColorPicker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbColorPicker, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcColorPicker = lv_colorwheel_create(ui_ScreenColorPicker, true);
    lv_colorwheel_set_mode_fixed(ui_ArcColorPicker, true);
    lv_obj_set_width(ui_ArcColorPicker, 300);
    lv_obj_set_height(ui_ArcColorPicker, 300);
    lv_obj_set_x(ui_ArcColorPicker, 200);
    lv_obj_set_y(ui_ArcColorPicker, 0);
    lv_obj_set_align(ui_ArcColorPicker, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_ArcColorPicker, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbArcColorPickerText = lv_label_create(ui_ArcColorPicker);
    lv_obj_set_width(ui_LbArcColorPickerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbArcColorPickerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbArcColorPickerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbArcColorPickerText, "Color Picker");
    lv_obj_set_style_text_color(ui_LbArcColorPickerText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbArcColorPickerText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBrightness = lv_arc_create(ui_ScreenColorPicker);
    lv_obj_set_width(ui_ArcBrightness, 300);
    lv_obj_set_height(ui_ArcBrightness, 300);
    lv_obj_set_x(ui_ArcBrightness, -200);
    lv_obj_set_y(ui_ArcBrightness, 0);
    lv_obj_set_align(ui_ArcBrightness, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcBrightness, 3, 255);
    lv_arc_set_value(ui_ArcBrightness, 50);
    lv_obj_set_style_arc_color(ui_ArcBrightness, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcBrightness, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_ArcBrightness, &ui_img_arch_gradient_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcBrightness, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_ArcBrightness, &ui_img_arch_gradient_bg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcBrightness, lv_color_hex(0xD7A24E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcBrightness, lv_color_hex(0xE3DCDC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ArcBrightness, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LbArcBrightnessText = lv_label_create(ui_ArcBrightness);
    lv_obj_set_width(ui_LbArcBrightnessText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbArcBrightnessText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbArcBrightnessText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbArcBrightnessText, "Brightness");
    lv_obj_set_style_text_color(ui_LbArcBrightnessText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbArcBrightnessText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    // ui_BtnSc3Right = lv_btn_create(ui_ScreenColorPicker);
    // lv_obj_set_width(ui_BtnSc3Right, 40);
    // lv_obj_set_height(ui_BtnSc3Right, 29);
    // lv_obj_set_x(ui_BtnSc3Right, 377);
    // lv_obj_set_y(ui_BtnSc3Right, 222);
    // lv_obj_set_align(ui_BtnSc3Right, LV_ALIGN_CENTER);
    // lv_obj_set_style_radius(ui_BtnSc3Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_BtnSc3Right, lv_color_hex(0x58F7D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_BtnSc3Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_src(ui_BtnSc3Right, &ui_img_arrow3_r_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_opa(ui_BtnSc3Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_BtnSc3Left = lv_btn_create(ui_ScreenColorPicker);
    // lv_obj_set_width(ui_BtnSc3Left, 40);
    // lv_obj_set_height(ui_BtnSc3Left, 29);
    // lv_obj_set_x(ui_BtnSc3Left, -377);
    // lv_obj_set_y(ui_BtnSc3Left, 222);
    // lv_obj_set_align(ui_BtnSc3Left, LV_ALIGN_CENTER);
    // lv_obj_set_style_radius(ui_BtnSc3Left, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_BtnSc3Left, lv_color_hex(0x58F7D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_BtnSc3Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_src(ui_BtnSc3Left, &ui_img_arrow3_l_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_img_opa(ui_BtnSc3Left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnColorPickerDone, ui_event_BtnColorPickerDone, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_BtnSc3Left, ui_event_BtnSc3Left, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_BtnSc3Right, ui_event_BtnSc3Right, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcColorPicker, ui_event_ArcColorPicker, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBrightness, ui_event_ArcBrightness, LV_EVENT_ALL, NULL);

}
