// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenLightControl_screen_init(void)
{
    ui_ScreenLightControl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenLightControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLightControl, lv_color_hex(0x06374B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLightControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLightControl = lv_obj_create(ui_ScreenLightControl);
    lv_obj_set_width(ui_PanelLightControl, 750);
    lv_obj_set_height(ui_PanelLightControl, 400);
    lv_obj_set_x(ui_PanelLightControl, 1);
    lv_obj_set_y(ui_PanelLightControl, 25);
    lv_obj_set_align(ui_PanelLightControl, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLightControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_PanelLightControl, lv_color_hex(0xFDF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLightControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLightControl, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLightControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLightStrip = lv_obj_create(ui_PanelLightControl);
    lv_obj_remove_style_all(ui_ContainerLightStrip);
    lv_obj_set_width(ui_ContainerLightStrip, 160);
    lv_obj_set_height(ui_ContainerLightStrip, 330);
    lv_obj_set_x(ui_ContainerLightStrip, -262);
    lv_obj_set_y(ui_ContainerLightStrip, 10);
    lv_obj_set_align(ui_ContainerLightStrip, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLightStrip, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_ContainerLightStrip, lv_color_hex(0x5C5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerLightStrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerLightStrip, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerLightStrip, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchLightStripOnOff = lv_btn_create(ui_ContainerLightStrip);
    lv_obj_set_width(ui_SwitchLightStripOnOff, 150);
    lv_obj_set_height(ui_SwitchLightStripOnOff, 150);
    lv_obj_set_x(ui_SwitchLightStripOnOff, 0);
    lv_obj_set_y(ui_SwitchLightStripOnOff, -85);
    lv_obj_set_align(ui_SwitchLightStripOnOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchLightStripOnOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchLightStripOnOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchLightStripOnOff, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchLightStripOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwitchLightStripOnOff, lv_color_hex(0x8E7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SwitchLightStripOnOff, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SwitchLightStripOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SwitchLightStripOnOff, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SwitchLightStripOnOff, lv_color_hex(0x076CB2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SwitchLightStripOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SwitchLightStripOnOff, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SwitchLightStripOnOff, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwLightStripStatusText = lv_label_create(ui_SwitchLightStripOnOff);
    lv_obj_set_width(ui_LbSwLightStripStatusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwLightStripStatusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwLightStripStatusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwLightStripStatusText, "-");
    lv_obj_set_style_text_font(ui_LbSwLightStripStatusText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwLightStripBrightness = lv_btn_create(ui_ContainerLightStrip);
    lv_obj_set_width(ui_LbSwLightStripBrightness, 150);
    lv_obj_set_height(ui_LbSwLightStripBrightness, 150);
    lv_obj_set_x(ui_LbSwLightStripBrightness, -1);
    lv_obj_set_y(ui_LbSwLightStripBrightness, 85);
    lv_obj_set_align(ui_LbSwLightStripBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LbSwLightStripBrightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LbSwLightStripBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LbSwLightStripBrightness, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LbSwLightStripBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LbSwLightStripBrightness, lv_color_hex(0x8E7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_LbSwLightStripBrightness, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LbSwLightStripBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LbSwLightStripBrightness, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LbSwLightStripBrightness, lv_color_hex(0xB8E925), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LbSwLightStripBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LbSwLightStripBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LbSwLightStripBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwBriDesc = lv_label_create(ui_LbSwLightStripBrightness);
    lv_obj_set_width(ui_LbSwBriDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwBriDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwBriDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwBriDesc, "Brightness");
    lv_obj_set_style_text_color(ui_LbSwBriDesc, lv_color_hex(0x090661), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwBriDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LbSwBriDesc, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwBriDesc, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRGBLamp1 = lv_obj_create(ui_PanelLightControl);
    lv_obj_remove_style_all(ui_ContainerRGBLamp1);
    lv_obj_set_width(ui_ContainerRGBLamp1, 160);
    lv_obj_set_height(ui_ContainerRGBLamp1, 330);
    lv_obj_set_x(ui_ContainerRGBLamp1, -88);
    lv_obj_set_y(ui_ContainerRGBLamp1, 10);
    lv_obj_set_align(ui_ContainerRGBLamp1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerRGBLamp1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_ContainerRGBLamp1, lv_color_hex(0x5C5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerRGBLamp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerRGBLamp1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerRGBLamp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchRGBLamp1OnOff = lv_btn_create(ui_ContainerRGBLamp1);
    lv_obj_set_width(ui_SwitchRGBLamp1OnOff, 150);
    lv_obj_set_height(ui_SwitchRGBLamp1OnOff, 150);
    lv_obj_set_x(ui_SwitchRGBLamp1OnOff, 0);
    lv_obj_set_y(ui_SwitchRGBLamp1OnOff, -85);
    lv_obj_set_align(ui_SwitchRGBLamp1OnOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchRGBLamp1OnOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchRGBLamp1OnOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchRGBLamp1OnOff, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchRGBLamp1OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwitchRGBLamp1OnOff, lv_color_hex(0x8E7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SwitchRGBLamp1OnOff, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SwitchRGBLamp1OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SwitchRGBLamp1OnOff, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SwitchRGBLamp1OnOff, lv_color_hex(0x076CB2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SwitchRGBLamp1OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SwitchRGBLamp1OnOff, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SwitchRGBLamp1OnOff, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp1StatusText = lv_label_create(ui_SwitchRGBLamp1OnOff);
    lv_obj_set_width(ui_LbSwRGBLamp1StatusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp1StatusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwRGBLamp1StatusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp1StatusText, "-");
    lv_obj_set_style_text_font(ui_LbSwRGBLamp1StatusText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp1ColorAndBrightness = lv_btn_create(ui_ContainerRGBLamp1);
    lv_obj_set_width(ui_LbSwRGBLamp1ColorAndBrightness, 150);
    lv_obj_set_height(ui_LbSwRGBLamp1ColorAndBrightness, 150);
    lv_obj_set_x(ui_LbSwRGBLamp1ColorAndBrightness, -1);
    lv_obj_set_y(ui_LbSwRGBLamp1ColorAndBrightness, 85);
    lv_obj_set_align(ui_LbSwRGBLamp1ColorAndBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LbSwRGBLamp1ColorAndBrightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LbSwRGBLamp1ColorAndBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LbSwRGBLamp1ColorAndBrightness, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LbSwRGBLamp1ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LbSwRGBLamp1ColorAndBrightness, lv_color_hex(0x8E7D7D),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_LbSwRGBLamp1ColorAndBrightness, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LbSwRGBLamp1ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LbSwRGBLamp1ColorAndBrightness, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LbSwRGBLamp1ColorAndBrightness, lv_color_hex(0xB8E925),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LbSwRGBLamp1ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LbSwRGBLamp1ColorAndBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LbSwRGBLamp1ColorAndBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp1ColAndBriDesc = lv_label_create(ui_LbSwRGBLamp1ColorAndBrightness);
    lv_obj_set_width(ui_LbSwRGBLamp1ColAndBriDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp1ColAndBriDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwRGBLamp1ColAndBriDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp1ColAndBriDesc, "Color\nBrightness");
    lv_obj_set_style_text_color(ui_LbSwRGBLamp1ColAndBriDesc, lv_color_hex(0x090661), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwRGBLamp1ColAndBriDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LbSwRGBLamp1ColAndBriDesc, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwRGBLamp1ColAndBriDesc, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRGBLamp2 = lv_obj_create(ui_PanelLightControl);
    lv_obj_remove_style_all(ui_ContainerRGBLamp2);
    lv_obj_set_width(ui_ContainerRGBLamp2, 160);
    lv_obj_set_height(ui_ContainerRGBLamp2, 330);
    lv_obj_set_x(ui_ContainerRGBLamp2, 88);
    lv_obj_set_y(ui_ContainerRGBLamp2, 10);
    lv_obj_set_align(ui_ContainerRGBLamp2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerRGBLamp2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_ContainerRGBLamp2, lv_color_hex(0x5C5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerRGBLamp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerRGBLamp2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerRGBLamp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchRGBLamp2OnOff = lv_btn_create(ui_ContainerRGBLamp2);
    lv_obj_set_width(ui_SwitchRGBLamp2OnOff, 150);
    lv_obj_set_height(ui_SwitchRGBLamp2OnOff, 150);
    lv_obj_set_x(ui_SwitchRGBLamp2OnOff, 0);
    lv_obj_set_y(ui_SwitchRGBLamp2OnOff, -85);
    lv_obj_set_align(ui_SwitchRGBLamp2OnOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchRGBLamp2OnOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchRGBLamp2OnOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchRGBLamp2OnOff, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchRGBLamp2OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwitchRGBLamp2OnOff, lv_color_hex(0x8E7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SwitchRGBLamp2OnOff, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SwitchRGBLamp2OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SwitchRGBLamp2OnOff, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SwitchRGBLamp2OnOff, lv_color_hex(0x076CB2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SwitchRGBLamp2OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SwitchRGBLamp2OnOff, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SwitchRGBLamp2OnOff, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp2StatusText = lv_label_create(ui_SwitchRGBLamp2OnOff);
    lv_obj_set_width(ui_LbSwRGBLamp2StatusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp2StatusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwRGBLamp2StatusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp2StatusText, "-");
    lv_obj_set_style_text_font(ui_LbSwRGBLamp2StatusText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp2ColorAndBrightness = lv_btn_create(ui_ContainerRGBLamp2);
    lv_obj_set_width(ui_LbSwRGBLamp2ColorAndBrightness, 150);
    lv_obj_set_height(ui_LbSwRGBLamp2ColorAndBrightness, 150);
    lv_obj_set_x(ui_LbSwRGBLamp2ColorAndBrightness, -1);
    lv_obj_set_y(ui_LbSwRGBLamp2ColorAndBrightness, 85);
    lv_obj_set_align(ui_LbSwRGBLamp2ColorAndBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LbSwRGBLamp2ColorAndBrightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LbSwRGBLamp2ColorAndBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LbSwRGBLamp2ColorAndBrightness, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LbSwRGBLamp2ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LbSwRGBLamp2ColorAndBrightness, lv_color_hex(0x8E7D7D),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_LbSwRGBLamp2ColorAndBrightness, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LbSwRGBLamp2ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LbSwRGBLamp2ColorAndBrightness, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LbSwRGBLamp2ColorAndBrightness, lv_color_hex(0xB8E925),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LbSwRGBLamp2ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_LbSwRGBLamp2ColorAndBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_LbSwRGBLamp2ColorAndBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp2ColAndBriDesc = lv_label_create(ui_LbSwRGBLamp2ColorAndBrightness);
    lv_obj_set_width(ui_LbSwRGBLamp2ColAndBriDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp2ColAndBriDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwRGBLamp2ColAndBriDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp2ColAndBriDesc, "Color\nBrightness");
    lv_obj_set_style_text_color(ui_LbSwRGBLamp2ColAndBriDesc, lv_color_hex(0x090661), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwRGBLamp2ColAndBriDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LbSwRGBLamp2ColAndBriDesc, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwRGBLamp2ColAndBriDesc, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerRGBLamp3 = lv_obj_create(ui_PanelLightControl);
    lv_obj_remove_style_all(ui_ContainerRGBLamp3);
    lv_obj_set_width(ui_ContainerRGBLamp3, 160);
    lv_obj_set_height(ui_ContainerRGBLamp3, 330);
    lv_obj_set_x(ui_ContainerRGBLamp3, 262);
    lv_obj_set_y(ui_ContainerRGBLamp3, 10);
    lv_obj_set_align(ui_ContainerRGBLamp3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerRGBLamp3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_ContainerRGBLamp3, lv_color_hex(0x5C5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerRGBLamp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerRGBLamp3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerRGBLamp3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchRGBLamp3OnOff = lv_btn_create(ui_ContainerRGBLamp3);
    lv_obj_set_width(ui_SwitchRGBLamp3OnOff, 150);
    lv_obj_set_height(ui_SwitchRGBLamp3OnOff, 150);
    lv_obj_set_x(ui_SwitchRGBLamp3OnOff, 0);
    lv_obj_set_y(ui_SwitchRGBLamp3OnOff, -85);
    lv_obj_set_align(ui_SwitchRGBLamp3OnOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwitchRGBLamp3OnOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwitchRGBLamp3OnOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchRGBLamp3OnOff, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchRGBLamp3OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwitchRGBLamp3OnOff, lv_color_hex(0x8E7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SwitchRGBLamp3OnOff, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SwitchRGBLamp3OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SwitchRGBLamp3OnOff, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SwitchRGBLamp3OnOff, lv_color_hex(0x076CB2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SwitchRGBLamp3OnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SwitchRGBLamp3OnOff, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SwitchRGBLamp3OnOff, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp3StatusText = lv_label_create(ui_SwitchRGBLamp3OnOff);
    lv_obj_set_width(ui_LbSwRGBLamp3StatusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp3StatusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwRGBLamp3StatusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp3StatusText, "-");
    lv_obj_set_style_text_font(ui_LbSwRGBLamp3StatusText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwRGBLamp3ColorAndBrightness = lv_btn_create(ui_ContainerRGBLamp3);
    lv_obj_set_width(ui_SwRGBLamp3ColorAndBrightness, 150);
    lv_obj_set_height(ui_SwRGBLamp3ColorAndBrightness, 150);
    lv_obj_set_x(ui_SwRGBLamp3ColorAndBrightness, -1);
    lv_obj_set_y(ui_SwRGBLamp3ColorAndBrightness, 85);
    lv_obj_set_align(ui_SwRGBLamp3ColorAndBrightness, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SwRGBLamp3ColorAndBrightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SwRGBLamp3ColorAndBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwRGBLamp3ColorAndBrightness, lv_color_hex(0x425B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwRGBLamp3ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SwRGBLamp3ColorAndBrightness, lv_color_hex(0x8E7D7D),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SwRGBLamp3ColorAndBrightness, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SwRGBLamp3ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SwRGBLamp3ColorAndBrightness, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SwRGBLamp3ColorAndBrightness, lv_color_hex(0xB8E925),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SwRGBLamp3ColorAndBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SwRGBLamp3ColorAndBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SwRGBLamp3ColorAndBrightness, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp3ColAndBriDesc = lv_label_create(ui_SwRGBLamp3ColorAndBrightness);
    lv_obj_set_width(ui_LbSwRGBLamp3ColAndBriDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp3ColAndBriDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSwRGBLamp3ColAndBriDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp3ColAndBriDesc, "Color\nBrightness");
    lv_obj_set_style_text_color(ui_LbSwRGBLamp3ColAndBriDesc, lv_color_hex(0x090661), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwRGBLamp3ColAndBriDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LbSwRGBLamp3ColAndBriDesc, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwRGBLamp3ColAndBriDesc, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwLightStripDesc = lv_label_create(ui_PanelLightControl);
    lv_obj_set_width(ui_LbSwLightStripDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwLightStripDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbSwLightStripDesc, -262);
    lv_obj_set_y(ui_LbSwLightStripDesc, -175);
    lv_obj_set_align(ui_LbSwLightStripDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwLightStripDesc, "Light Strip");
    lv_obj_set_style_text_color(ui_LbSwLightStripDesc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwLightStripDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwLightStripDesc, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp1Desc = lv_label_create(ui_PanelLightControl);
    lv_obj_set_width(ui_LbSwRGBLamp1Desc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp1Desc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbSwRGBLamp1Desc, -88);
    lv_obj_set_y(ui_LbSwRGBLamp1Desc, -175);
    lv_obj_set_align(ui_LbSwRGBLamp1Desc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp1Desc, "RGB Lamp 1");
    lv_obj_set_style_text_color(ui_LbSwRGBLamp1Desc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwRGBLamp1Desc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwRGBLamp1Desc, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp2Desc = lv_label_create(ui_PanelLightControl);
    lv_obj_set_width(ui_LbSwRGBLamp2Desc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp2Desc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbSwRGBLamp2Desc, 88);
    lv_obj_set_y(ui_LbSwRGBLamp2Desc, -175);
    lv_obj_set_align(ui_LbSwRGBLamp2Desc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp2Desc, "RGB Lamp 2");
    lv_obj_set_style_text_color(ui_LbSwRGBLamp2Desc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwRGBLamp2Desc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwRGBLamp2Desc, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSwRGBLamp3Desc = lv_label_create(ui_PanelLightControl);
    lv_obj_set_width(ui_LbSwRGBLamp3Desc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSwRGBLamp3Desc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbSwRGBLamp3Desc, 262);
    lv_obj_set_y(ui_LbSwRGBLamp3Desc, -175);
    lv_obj_set_align(ui_LbSwRGBLamp3Desc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSwRGBLamp3Desc, "RGB Lamp 3");
    lv_obj_set_style_text_color(ui_LbSwRGBLamp3Desc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbSwRGBLamp3Desc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbSwRGBLamp3Desc, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbLightControlHeader = lv_label_create(ui_ScreenLightControl);
    lv_obj_set_width(ui_LbLightControlHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbLightControlHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbLightControlHeader, 0);
    lv_obj_set_y(ui_LbLightControlHeader, -205);
    lv_obj_set_align(ui_LbLightControlHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbLightControlHeader, "LIGHT CONTROL");
    lv_obj_set_style_text_color(ui_LbLightControlHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbLightControlHeader, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_ScreenLightControl_previous = lv_btn_create(ui_ScreenLightControl);
    lv_obj_set_width(ui_ScreenLightControl_previous, 40);
    lv_obj_set_height(ui_ScreenLightControl_previous, 29);
    lv_obj_set_x(ui_ScreenLightControl_previous, -377);
    lv_obj_set_y(ui_ScreenLightControl_previous, 222);
    lv_obj_set_align(ui_ScreenLightControl_previous, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ScreenLightControl_previous, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenLightControl_previous, lv_color_hex(0x58F7D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLightControl_previous, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenLightControl_previous, &ui_img_arrow3_l_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ScreenLightControl_previous, 155, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenLightControl_next = lv_btn_create(ui_ScreenLightControl);
    lv_obj_set_width(ui_ScreenLightControl_next, 40);
    lv_obj_set_height(ui_ScreenLightControl_next, 29);
    lv_obj_set_x(ui_ScreenLightControl_next, 377);
    lv_obj_set_y(ui_ScreenLightControl_next, 222);
    lv_obj_set_align(ui_ScreenLightControl_next, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ScreenLightControl_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenLightControl_next, lv_color_hex(0x58F7D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLightControl_next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenLightControl_next, &ui_img_arrow3_r_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ScreenLightControl_next, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	
    lv_obj_add_event_cb(ui_ScreenLightControl_previous, ui_event_ScreenLightControl_previous, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenLightControl_next, ui_event_ScreenLightControl_next, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_LbSwLightStripBrightness, ui_event_SwLightStripBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchRGBLamp1OnOff, ui_event_SwitchRGBLamp1OnOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LbSwRGBLamp1ColorAndBrightness, ui_event_SwRGBLamp1ColorAndBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchRGBLamp2OnOff, ui_event_SwitchRGBLamp2OnOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LbSwRGBLamp2ColorAndBrightness, ui_event_SwRGBLamp2ColorAndBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchRGBLamp3OnOff, ui_event_SwitchRGBLamp3OnOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwRGBLamp3ColorAndBrightness, ui_event_SwRGBLamp3ColorAndBrightness, LV_EVENT_ALL, NULL);
        lv_obj_add_event_cb(ui_SwitchLightStripOnOff, ui_event_SwitchLightStripOnOff, LV_EVENT_ALL, NULL);
}
