// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "NumberDotsFont40.h"

void ui_ScreenWeather_screen_init(void)
{
    ui_ScreenWeather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    //lv_obj_set_style_bg_img_src(ui_ScreenWeather, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenWeather, lv_color_hex(0x06374B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ScreenWeather, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherHeader = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_WeatherHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherHeader, -164);
    lv_obj_set_y(ui_WeatherHeader, -200);
    lv_obj_set_align(ui_WeatherHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherHeader, "Weather Forcast");
    lv_obj_set_style_text_color(ui_WeatherHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherHeader, &ui_font_AnandaBlack40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherHeader1 = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_WeatherHeader1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherHeader1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherHeader1, 185);
    lv_obj_set_y(ui_WeatherHeader1, -200);
    lv_obj_set_align(ui_WeatherHeader1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherHeader1, "Indoor Temperature");
    lv_obj_set_style_text_color(ui_WeatherHeader1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WeatherHeader1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherHeader1, &ui_font_AnandaBlack40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconWeather = lv_img_create(ui_ScreenWeather);
    lv_img_set_src(ui_iconWeather, &ui_img_999054828);
    lv_obj_set_width(ui_iconWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconWeather, -355);
    lv_obj_set_y(ui_iconWeather, -200);
    lv_obj_set_align(ui_iconWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_iconWeather, &ui_img_999054828, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_iconTemp = lv_img_create(ui_ScreenWeather);
    lv_img_set_src(ui_iconTemp, &ui_img_1578496546);
    lv_obj_set_width(ui_iconTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconTemp, -360);
    lv_obj_set_y(ui_iconTemp, -105);
    lv_obj_set_align(ui_iconTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_iconTemp, 200);

    ui_iconAirPressure = lv_img_create(ui_ScreenWeather);
    lv_img_set_src(ui_iconAirPressure, &ui_img_1668089981);
    lv_obj_set_width(ui_iconAirPressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconAirPressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconAirPressure, -360);
    lv_obj_set_y(ui_iconAirPressure, -15);
    lv_obj_set_align(ui_iconAirPressure, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconAirPressure, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconAirPressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_iconAirPressure, 200);

    ui_iconAirHumidity = lv_img_create(ui_ScreenWeather);
    lv_img_set_src(ui_iconAirHumidity, &ui_img_947629812);
    lv_obj_set_width(ui_iconAirHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconAirHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconAirHumidity, -360);
    lv_obj_set_y(ui_iconAirHumidity, 75);
    lv_obj_set_align(ui_iconAirHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconAirHumidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconAirHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_iconAirHumidity, 200);

    ui_iconWindSpeed = lv_img_create(ui_ScreenWeather);
    lv_img_set_src(ui_iconWindSpeed, &ui_img_233333594);
    lv_obj_set_width(ui_iconWindSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iconWindSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iconWindSpeed, -360);
    lv_obj_set_y(ui_iconWindSpeed, 165);
    lv_obj_set_align(ui_iconWindSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iconWindSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iconWindSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_iconWindSpeed, 200);

    ui_ContainerWeatherForcast = lv_obj_create(ui_ScreenWeather);
    lv_obj_remove_style_all(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_ContainerWeatherForcast, 323);
    lv_obj_set_height(ui_ContainerWeatherForcast, 326);
    lv_obj_set_x(ui_ContainerWeatherForcast, -165);
    lv_obj_set_y(ui_ContainerWeatherForcast, 30);
    lv_obj_set_align(ui_ContainerWeatherForcast, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWeatherForcast, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerWeatherForcast, lv_color_hex(0x192D37), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerWeatherForcast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerWeatherForcast, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerWeatherForcast, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerWeatherForcast, lv_color_hex(0x335C71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerWeatherForcast, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerWeatherForcast, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerWeatherForcast, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbTempText1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbTempText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTempText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbTempText1, -70);
    lv_obj_set_y(ui_LbTempText1, -135);
    lv_obj_set_align(ui_LbTempText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbTempText1, "Temperature");
    lv_obj_set_style_text_color(ui_LbTempText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTempText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbTempText1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbPressureText1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbPressureText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbPressureText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbPressureText1, -70);
    lv_obj_set_y(ui_LbPressureText1, -45);
    lv_obj_set_align(ui_LbPressureText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbPressureText1, "Air pressure");
    lv_obj_set_style_text_color(ui_LbPressureText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbPressureText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbPressureText1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHumidityText1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbHumidityText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHumidityText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHumidityText1, -70);
    lv_obj_set_y(ui_LbHumidityText1, 45);
    lv_obj_set_align(ui_LbHumidityText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbHumidityText1, "Air humidity");
    lv_obj_set_style_text_color(ui_LbHumidityText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHumidityText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHumidityText1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbWindspeedText1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbWindspeedText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbWindspeedText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbWindspeedText1, -70);
    lv_obj_set_y(ui_LbWindspeedText1, 135);
    lv_obj_set_align(ui_LbWindspeedText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbWindspeedText1, "Wind speed");
    lv_obj_set_style_text_color(ui_LbWindspeedText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbWindspeedText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbWindspeedText1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbTempValue1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbTempValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTempValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbTempValue1, 55);
    lv_obj_set_y(ui_LbTempValue1, -135);
    lv_obj_set_align(ui_LbTempValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbTempValue1, "00.0");
    lv_obj_set_style_text_color(ui_LbTempValue1, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTempValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbTempValue1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbPressureValue1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbPressureValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbPressureValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbPressureValue1, 55);
    lv_obj_set_y(ui_LbPressureValue1, -45);
    lv_obj_set_align(ui_LbPressureValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbPressureValue1, "00.0");
    lv_obj_set_style_text_color(ui_LbPressureValue1, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbPressureValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbPressureValue1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHumidityValue1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbHumidityValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHumidityValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHumidityValue1, 55);
    lv_obj_set_y(ui_LbHumidityValue1, 45);
    lv_obj_set_align(ui_LbHumidityValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbHumidityValue1, "00.0");
    lv_obj_set_style_text_color(ui_LbHumidityValue1, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHumidityValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHumidityValue1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbWindspeedValue1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbWindspeedValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbWindspeedValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbWindspeedValue1, 55);
    lv_obj_set_y(ui_LbWindspeedValue1, 135);
    lv_obj_set_align(ui_LbWindspeedValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbWindspeedValue1, "00.0");
    lv_obj_set_style_text_color(ui_LbWindspeedValue1, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbWindspeedValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbWindspeedValue1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbTempUnit1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbTempUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTempUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbTempUnit1, 120);
    lv_obj_set_y(ui_LbTempUnit1, -135);
    lv_obj_set_align(ui_LbTempUnit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbTempUnit1, "°C");
    lv_obj_set_style_text_color(ui_LbTempUnit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTempUnit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbTempUnit1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbPressureUnit1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbPressureUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbPressureUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbPressureUnit1, 130);
    lv_obj_set_y(ui_LbPressureUnit1, -45);
    lv_obj_set_align(ui_LbPressureUnit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbPressureUnit1, "hPa");
    lv_obj_set_style_text_color(ui_LbPressureUnit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbPressureUnit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbPressureUnit1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHumidityUnit1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbHumidityUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHumidityUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHumidityUnit1, 120);
    lv_obj_set_y(ui_LbHumidityUnit1, 45);
    lv_obj_set_align(ui_LbHumidityUnit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbHumidityUnit1, "%");
    lv_obj_set_style_text_color(ui_LbHumidityUnit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHumidityUnit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHumidityUnit1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbWindspeedUnit1 = lv_label_create(ui_ContainerWeatherForcast);
    lv_obj_set_width(ui_LbWindspeedUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbWindspeedUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbWindspeedUnit1, 130);
    lv_obj_set_y(ui_LbWindspeedUnit1, 135);
    lv_obj_set_align(ui_LbWindspeedUnit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbWindspeedUnit1, "km/h");
    lv_obj_set_style_text_color(ui_LbWindspeedUnit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbWindspeedUnit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbWindspeedUnit1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerIndoorTemp = lv_obj_create(ui_ScreenWeather);
    lv_obj_remove_style_all(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_ContainerIndoorTemp, 323);
    lv_obj_set_height(ui_ContainerIndoorTemp, 326);
    lv_obj_set_x(ui_ContainerIndoorTemp, 196);
    lv_obj_set_y(ui_ContainerIndoorTemp, 30);
    lv_obj_set_align(ui_ContainerIndoorTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerIndoorTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerIndoorTemp, lv_color_hex(0x192D37), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerIndoorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerIndoorTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerIndoorTemp, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ContainerIndoorTemp, lv_color_hex(0x335C71), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ContainerIndoorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ContainerIndoorTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ContainerIndoorTemp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbTempText2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbTempText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTempText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbTempText2, -70);
    lv_obj_set_y(ui_LbTempText2, -135);
    lv_obj_set_align(ui_LbTempText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbTempText2, "Temperature");
    lv_obj_set_style_text_color(ui_LbTempText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTempText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbTempText2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbPressureText2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbPressureText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbPressureText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbPressureText2, -70);
    lv_obj_set_y(ui_LbPressureText2, -45);
    lv_obj_set_align(ui_LbPressureText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbPressureText2, "Air pressure");
    lv_obj_set_style_text_color(ui_LbPressureText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbPressureText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbPressureText2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHumidityText2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbHumidityText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHumidityText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHumidityText2, -70);
    lv_obj_set_y(ui_LbHumidityText2, 45);
    lv_obj_set_align(ui_LbHumidityText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbHumidityText2, "Air humidity");
    lv_obj_set_style_text_color(ui_LbHumidityText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHumidityText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHumidityText2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbWindspeedText2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbWindspeedText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbWindspeedText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbWindspeedText2, -70);
    lv_obj_set_y(ui_LbWindspeedText2, 135);
    lv_obj_set_align(ui_LbWindspeedText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbWindspeedText2, "Wind speed");
    lv_obj_set_style_text_color(ui_LbWindspeedText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbWindspeedText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbWindspeedText2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbTempValue2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbTempValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTempValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbTempValue2, 55);
    lv_obj_set_y(ui_LbTempValue2, -135);
    lv_obj_set_align(ui_LbTempValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbTempValue2, "00.0");
    lv_obj_set_style_text_color(ui_LbTempValue2, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTempValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbTempValue2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbPressureValue2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbPressureValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbPressureValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbPressureValue2, 55);
    lv_obj_set_y(ui_LbPressureValue2, -45);
    lv_obj_set_align(ui_LbPressureValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbPressureValue2, "00.0");
    lv_obj_set_style_text_color(ui_LbPressureValue2, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbPressureValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbPressureValue2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHumidityValue2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbHumidityValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHumidityValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHumidityValue2, 55);
    lv_obj_set_y(ui_LbHumidityValue2, 45);
    lv_obj_set_align(ui_LbHumidityValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbHumidityValue2, "00.0");
    lv_obj_set_style_text_color(ui_LbHumidityValue2, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHumidityValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHumidityValue2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbWindspeedValue2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbWindspeedValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbWindspeedValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbWindspeedValue2, 55);
    lv_obj_set_y(ui_LbWindspeedValue2, 135);
    lv_obj_set_align(ui_LbWindspeedValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbWindspeedValue2, "00.0");
    lv_obj_set_style_text_color(ui_LbWindspeedValue2, lv_color_hex(0xF27414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbWindspeedValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbWindspeedValue2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbTempUnit2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbTempUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTempUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbTempUnit2, 120);
    lv_obj_set_y(ui_LbTempUnit2, -135);
    lv_obj_set_align(ui_LbTempUnit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbTempUnit2, "°C");
    lv_obj_set_style_text_color(ui_LbTempUnit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTempUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbTempUnit2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbPressureUnit2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbPressureUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbPressureUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbPressureUnit2, 130);
    lv_obj_set_y(ui_LbPressureUnit2, -45);
    lv_obj_set_align(ui_LbPressureUnit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbPressureUnit2, "hPa");
    lv_obj_set_style_text_color(ui_LbPressureUnit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbPressureUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbPressureUnit2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbHumidityUnit2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbHumidityUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHumidityUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbHumidityUnit2, 120);
    lv_obj_set_y(ui_LbHumidityUnit2, 45);
    lv_obj_set_align(ui_LbHumidityUnit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbHumidityUnit2, "%");
    lv_obj_set_style_text_color(ui_LbHumidityUnit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHumidityUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbHumidityUnit2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbWindspeedUnit2 = lv_label_create(ui_ContainerIndoorTemp);
    lv_obj_set_width(ui_LbWindspeedUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbWindspeedUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbWindspeedUnit2, 130);
    lv_obj_set_y(ui_LbWindspeedUnit2, 135);
    lv_obj_set_align(ui_LbWindspeedUnit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbWindspeedUnit2, "km/h");
    lv_obj_set_style_text_color(ui_LbWindspeedUnit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbWindspeedUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbWindspeedUnit2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbTimeAndDate = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_LbTimeAndDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTimeAndDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbTimeAndDate, 17);
    lv_obj_set_y(ui_LbTimeAndDate, 218);
    lv_obj_set_align(ui_LbTimeAndDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbTimeAndDate, "00:00, 2001-01-01");
    lv_obj_set_style_text_color(ui_LbTimeAndDate, lv_color_hex(0xFAF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTimeAndDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbTimeAndDate, &ui_font_NumberDotsFont30, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Image1 = ui_iconWeather;

    ui_ScreenWeather_previous = lv_btn_create(ui_ScreenWeather);
    lv_obj_set_width(ui_ScreenWeather_previous, 40);
    lv_obj_set_height(ui_ScreenWeather_previous, 29);
    lv_obj_set_x(ui_ScreenWeather_previous, -377);
    lv_obj_set_y(ui_ScreenWeather_previous, 222);
    lv_obj_set_align(ui_ScreenWeather_previous, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ScreenWeather_previous, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenWeather_previous, lv_color_hex(0x06374B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWeather_previous, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenWeather_previous, &ui_img_arrow3_l_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ScreenWeather_previous, 155, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenWeather_next = lv_btn_create(ui_ScreenWeather);
    lv_obj_set_width(ui_ScreenWeather_next, 40);
    lv_obj_set_height(ui_ScreenWeather_next, 29);
    lv_obj_set_x(ui_ScreenWeather_next, 377);
    lv_obj_set_y(ui_ScreenWeather_next, 222);
    lv_obj_set_align(ui_ScreenWeather_next, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ScreenWeather_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenWeather_next, lv_color_hex(0x06374B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWeather_next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScreenWeather_next, &ui_img_arrow3_r_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ScreenWeather_next, 155, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSc1LoadStatus = lv_label_create(ui_ScreenWeather);
    lv_obj_set_width(ui_lbSc1LoadStatus, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_lbSc1LoadStatus, LV_SIZE_CONTENT); 
    lv_obj_set_x(ui_lbSc1LoadStatus, 0);
    lv_obj_set_y(ui_lbSc1LoadStatus, 225);
    lv_obj_set_align(ui_lbSc1LoadStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSc1LoadStatus, "Loading new screen. Please, wait ...");
    lv_obj_add_flag(ui_lbSc1LoadStatus, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_lbSc1LoadStatus,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lbSc1LoadStatus, lv_color_hex(0x034905), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSc1LoadStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenWeather_previous, ui_event_ScreenWeather_previous, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenWeather_next, ui_event_ScreenWeather_next, LV_EVENT_ALL, NULL);
}
