// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../data.h"

void ui_ScreenColorTemp_screen_init(void)
{
    ui_ScreenColorTemp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenColorTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenColorTemp, lv_color_hex(0x06374B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenColorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnColorTempDone = lv_btn_create(ui_ScreenColorTemp);
    lv_obj_set_width(ui_BtnColorTempDone, 136);
    lv_obj_set_height(ui_BtnColorTempDone, 48);
    lv_obj_set_x(ui_BtnColorTempDone, 0);
    lv_obj_set_y(ui_BtnColorTempDone, 200);
    lv_obj_set_align(ui_BtnColorTempDone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnColorTempDone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnColorTempDone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_BtnColorTempDone, lv_color_hex(0xB1A7A7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BtnColorTempDone, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbColorTempBtnText = lv_label_create(ui_BtnColorTempDone);
    lv_obj_set_width(ui_LbColorTempBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbColorTempBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbColorTempBtnText, -1);
    lv_obj_set_y(ui_LbColorTempBtnText, -1);
    lv_obj_set_align(ui_LbColorTempBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbColorTempBtnText, "DONE");
    lv_obj_set_style_text_color(ui_LbColorTempBtnText, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbColorTempBtnText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbColorTempBtnText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelColorTemp = lv_obj_create(ui_ScreenColorTemp);
    lv_obj_set_width(ui_PanelColorTemp, 752);
    lv_obj_set_height(ui_PanelColorTemp, 336);
    lv_obj_set_align(ui_PanelColorTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelColorTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelColorTemp, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelColorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbColorTemp = lv_label_create(ui_ScreenColorTemp);
    lv_obj_set_width(ui_LbColorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbColorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbColorTemp, 0);
    lv_obj_set_y(ui_LbColorTemp, -200);
    lv_obj_set_align(ui_LbColorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbColorTemp, "COLOR PICKER");
    lv_obj_set_style_text_color(ui_LbColorTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbColorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbColorTemp, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcColorTempsLightStrip = lv_arc_create(ui_ScreenColorTemp);
    lv_obj_set_width(ui_ArcColorTempsLightStrip, 300);
    lv_obj_set_height(ui_ArcColorTempsLightStrip, 300);
    lv_obj_set_x(ui_ArcColorTempsLightStrip, 200);
    lv_obj_set_y(ui_ArcColorTempsLightStrip, 0);
    lv_obj_set_align(ui_ArcColorTempsLightStrip, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcColorTempsLightStrip, 153, 500);
    lv_arc_set_value(ui_ArcColorTempsLightStrip, 50);
    lv_obj_set_style_arc_color(ui_ArcColorTempsLightStrip, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcColorTempsLightStrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcColorTempsLightStrip, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_ArcColorTempsLightStrip, &ui_img_colortemp_cicle_2_png,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcColorTempsLightStrip, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_ArcColorTempsLightStrip, &ui_img_colortemp_cicle_2_png,
                                 LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcColorTempsLightStrip, lv_color_hex(0xD7A24E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcColorTempsLightStrip, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcColorTempsLightStrip, lv_color_hex(0xE3DCDC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ArcColorTempsLightStrip, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_DEFAULT);


    ui_LbArcLightStripColorTempText = lv_label_create(ui_ArcColorTempsLightStrip);
    lv_obj_set_width(ui_LbArcLightStripColorTempText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbArcLightStripColorTempText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbArcLightStripColorTempText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbArcLightStripColorTempText, "Color Temp");
    lv_obj_set_style_text_color(ui_LbArcLightStripColorTempText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbArcLightStripColorTempText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBrightnessLightStrip = lv_arc_create(ui_ScreenColorTemp);
    lv_obj_set_width(ui_ArcBrightnessLightStrip, 300);
    lv_obj_set_height(ui_ArcBrightnessLightStrip, 300);
    lv_obj_set_x(ui_ArcBrightnessLightStrip, -200);
    lv_obj_set_y(ui_ArcBrightnessLightStrip, 0);
    lv_obj_set_align(ui_ArcBrightnessLightStrip, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcBrightnessLightStrip, 3, 255);
    lv_arc_set_value(ui_ArcBrightnessLightStrip, 50);
    lv_obj_set_style_arc_color(ui_ArcBrightnessLightStrip, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBrightnessLightStrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcBrightnessLightStrip, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_ArcBrightnessLightStrip, &ui_img_arch_gradient_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcBrightnessLightStrip, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_ArcBrightnessLightStrip, &ui_img_arch_gradient_bg_png,
                                 LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcBrightnessLightStrip, lv_color_hex(0xD7A24E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBrightnessLightStrip, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcBrightnessLightStrip, lv_color_hex(0xE3DCDC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ArcBrightnessLightStrip, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LbArcLightStripBriText = lv_label_create(ui_ArcBrightnessLightStrip);
    lv_obj_set_width(ui_LbArcLightStripBriText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbArcLightStripBriText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbArcLightStripBriText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbArcLightStripBriText, "Brightness");
    lv_obj_set_style_text_color(ui_LbArcLightStripBriText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbArcLightStripBriText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnColorTempDone, ui_event_BtnColorTempDone, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBrightnessLightStrip, ui_event_ArcBrightnessLightStrip, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcColorTempsLightStrip, ui_event_ArcColorTempsLightStrip, LV_EVENT_ALL, NULL);

    

    

}
